import mongoose from 'mongoose';
import dns from 'node:dns';
import dotenv from 'dotenv';
import path from 'path';
import Sponsorship from '../models/Sponsorship';

try {
  dns.setServers(['8.8.8.8', '1.1.1.1', '8.8.4.4']);
} catch {}

// Load env vars
dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(process.cwd(), 'apps/web/.env') });

const MONGODB_URL = process.env.MONGODB_URL;

if (!MONGODB_URL) {
  console.error('Please define the MONGODB_URL environment variable inside .env');
  process.exit(1);
}

export const SPONSORSHIPS_DATA = [
  // ==========================================
  // 1. ALL SPORTS / GLOBAL VIP (5 Items)
  // ==========================================
  {
    title: 'GoalMills VIP Match Centre 2026',
    sponsorName: 'GoalMills Global & Nike Pro',
    sponsorLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/vip-pass',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
    tagline: 'Unlock Ultra-HD 4K live streams, multi-camera tactical view, and real-time AI predictive match analytics.',
    ctaText: 'Claim VIP Pass',
    sportSlug: 'all',
    badgeText: 'VIP PLATINUM',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 48200,
    clicks: 3940,
    budget: 25000,
    isDeleted: false,
  },
  {
    title: 'Apex Sports Nutrition & Hydration',
    sponsorName: 'Apex Labs International',
    sponsorLogo: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/apex-nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    tagline: 'Fuel peak athletic performance and rapid muscle recovery with scientifically certified isotonic formulas.',
    ctaText: 'Get 25% Off',
    sportSlug: 'all',
    badgeText: 'OFFICIAL PARTNER',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 29500,
    clicks: 2180,
    budget: 12000,
    isDeleted: false,
  },
  {
    title: 'HydraFit Smart Telemetry Wearable',
    sponsorName: 'HydraFit Sports Tech',
    sponsorLogo: 'https://images.unsplash.com/photo-1576243345690-4e4b79b63288?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/hydrafit-sensor',
    imageUrl: 'https://images.unsplash.com/photo-1510519138171-c70d76b54a45?w=800&auto=format&fit=crop&q=80',
    tagline: 'Millisecond-precision heart rate, sprint burst velocity, and metabolic stamina tracking for athletes.',
    ctaText: 'Explore Wearable',
    sportSlug: 'all',
    badgeText: 'TECH INNOVATION',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 18400,
    clicks: 1420,
    budget: 9500,
    isDeleted: false,
  },
  {
    title: 'BetPulse High-Stakes Sports Odds',
    sponsorName: 'BetPulse Premier',
    sponsorLogo: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=120&auto=format&fit=crop&q=80',
    type: 'affiliate_link',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/betpulse-boost',
    imageUrl: 'https://images.unsplash.com/photo-1471295253337-3ceaaedca402?w=800&auto=format&fit=crop&q=80',
    tagline: 'Zero-margin enhanced odds, live in-play cashouts, and £50 welcome betting bonus for new players.',
    ctaText: 'Claim £50 Bonus',
    sportSlug: 'all',
    badgeText: 'ODDS BOOST',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 34100,
    clicks: 2910,
    budget: 18000,
    isDeleted: false,
  },
  {
    title: 'GoalMills Sports Intelligence Dossier',
    sponsorName: 'GoalMills Media Network',
    sponsorLogo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/newsletter',
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&auto=format&fit=crop&q=80',
    tagline: 'Exclusive tactical breakdowns and scouting intelligence delivered weekly to 200,000+ subscribers.',
    ctaText: 'Subscribe Free',
    sportSlug: 'all',
    badgeText: 'NEWSLETTER EXCLUSIVE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 15300,
    clicks: 1670,
    budget: 5000,
    isDeleted: false,
  },

  // ==========================================
  // 2. FOOTBALL / SOCCER (5 Items)
  // ==========================================
  {
    title: 'Nike Mercurial Superfly Elite X',
    sponsorName: 'Nike Football Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/nike-football',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?w=800&auto=format&fit=crop&q=80',
    tagline: 'Explosive 3/4 Zoom Air unit tuned for lightning speed and razor-sharp cuts inside the penalty box.',
    ctaText: 'Shop Boots',
    sportSlug: 'football',
    badgeText: 'FEATURED BOOTS',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 62000,
    clicks: 5800,
    budget: 35000,
    isDeleted: false,
  },
  {
    title: 'adidas UCL Official Match Ball Pro',
    sponsorName: 'adidas Football',
    sponsorLogo: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/adidas-ucl',
    imageUrl: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=800&auto=format&fit=crop&q=80',
    tagline: 'Thermal-bonded seamless surface designed for pin-point accuracy during Champions League nights.',
    ctaText: 'Order Match Ball',
    sportSlug: 'football',
    badgeText: 'UCL OFFICIAL',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 41200,
    clicks: 3450,
    budget: 22000,
    isDeleted: false,
  },
  {
    title: 'Puma Future Ultimate Z Edition',
    sponsorName: 'PUMA Sports',
    sponsorLogo: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/puma-future',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80',
    tagline: 'Adaptive FUZIONFIT360 dual mesh upper with PWRTAPE lockdown for unmatched ball control.',
    ctaText: 'Get 20% Off',
    sportSlug: 'football',
    badgeText: 'EXCLUSIVE DEAL',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 27900,
    clicks: 1980,
    budget: 14000,
    isDeleted: false,
  },
  {
    title: 'Barça Tactical Analyst Masterclass',
    sponsorName: 'Barça Innovation Hub',
    sponsorLogo: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/barca-analytics',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&auto=format&fit=crop&q=80',
    tagline: 'Master high-press transitions, expected goals (xG) metrics, and tactical spatial dominance.',
    ctaText: 'Enroll Now',
    sportSlug: 'football',
    badgeText: 'PRO CERTIFIED',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 19800,
    clicks: 1420,
    budget: 8500,
    isDeleted: false,
  },
  {
    title: 'Premier League VIP Hospitality Club',
    sponsorName: 'Matchday Experiences UK',
    sponsorLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/premier-league-vip',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    tagline: 'Tunnel club access, luxury private boxes, and player meet & greets at all top Premier League fixtures.',
    ctaText: 'Book VIP Seats',
    sportSlug: 'football',
    badgeText: 'VIP HOSPITALITY',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 16500,
    clicks: 1380,
    budget: 9000,
    isDeleted: false,
  },

  // ==========================================
  // 3. CRICKET / IPL / T20 (5 Items)
  // ==========================================
  {
    title: 'SS Ton Heritage Grade 1+ English Willow',
    sponsorName: 'Sunridges Cricket International',
    sponsorLogo: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/ss-cricket',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    tagline: 'Handcrafted cleft with massive 42mm edges and featherweight balance for boundary clearing power.',
    ctaText: 'Explore Willow',
    sportSlug: 'cricket',
    badgeText: 'MASTER CRAFT',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 54000,
    clicks: 4700,
    budget: 28000,
    isDeleted: false,
  },
  {
    title: 'MRF Genius Grand Edition Virat Special',
    sponsorName: 'MRF Pace Foundation & Gear',
    sponsorLogo: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/mrf-cricket',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop&q=80',
    tagline: 'The world-famous signature profile engineered for precision cover drives and maximum stroke play.',
    ctaText: 'Order Signature Bat',
    sportSlug: 'cricket',
    badgeText: 'CHAMPIONS CHOICE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 38200,
    clicks: 3100,
    budget: 19500,
    isDeleted: false,
  },
  {
    title: 'SmartBall Radar: RPM & Bowling Speed Sensor',
    sponsorName: 'CricTech Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/crictech-radar',
    imageUrl: 'https://images.unsplash.com/photo-1512719355462-e7555dcf40ad?w=800&auto=format&fit=crop&q=80',
    tagline: 'Track real-time seam angle, revolutions per second, release height, and ball speed in real time.',
    ctaText: 'Try Telemetry',
    sportSlug: 'cricket',
    badgeText: 'AI TELEMETRY',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 22100,
    clicks: 1640,
    budget: 11000,
    isDeleted: false,
  },
  {
    title: 'Kookaburra Turf Regulation White Match Balls',
    sponsorName: 'Kookaburra Sports',
    sponsorLogo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/kookaburra-balls',
    imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800&auto=format&fit=crop&q=80',
    tagline: 'The official white ball of international cricket, World Cups, and premier global T20 franchise leagues.',
    ctaText: 'Shop Match Balls',
    sportSlug: 'cricket',
    badgeText: 'OFFICIAL MATCH',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 17800,
    clicks: 1290,
    budget: 7800,
    isDeleted: false,
  },
  {
    title: 'IPL 2026 VIP Dugout Experience Pass',
    sponsorName: 'CricPass Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/ipl-vip-pass',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    tagline: 'Front-row boundary lounge passes, player dining privileges, and authentic autographed team merchandise.',
    ctaText: 'Reserve IPL Pass',
    sportSlug: 'cricket',
    badgeText: 'VIP ACCESS',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 21400,
    clicks: 1890,
    budget: 13000,
    isDeleted: false,
  },

  // ==========================================
  // 4. BASKETBALL / NBA (5 Items)
  // ==========================================
  {
    title: 'Air Jordan 40 Retro Flight Performance',
    sponsorName: 'Jordan Brand & Nike',
    sponsorLogo: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/jordan-retro',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    tagline: 'Carbon-fiber FlightPlate technology with full-length Zoom Air Strobel for sky-high vertical lift.',
    ctaText: 'Claim Kicks',
    sportSlug: 'basketball',
    badgeText: 'JORDAN DROP',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 61000,
    clicks: 5400,
    budget: 32000,
    isDeleted: false,
  },
  {
    title: 'Wilson NBA Official Game Leather Basketball',
    sponsorName: 'Wilson Basketball Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/wilson-nba',
    imageUrl: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800&auto=format&fit=crop&q=80',
    tagline: '100% genuine Horween full-grain leather providing legendary grip and standard NBA game bounce.',
    ctaText: 'Buy Official Ball',
    sportSlug: 'basketball',
    badgeText: 'NBA OFFICIAL',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 34500,
    clicks: 2890,
    budget: 17500,
    isDeleted: false,
  },
  {
    title: 'Under Armour Curry Flow 12 Zero-Rubber',
    sponsorName: 'Under Armour Hoops',
    sponsorLogo: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/curry-flow',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
    tagline: 'Revolutionary UA Flow cushioning gives you zero-slip traction for rapid step-back 3-pointers.',
    ctaText: 'Shop Curry 12',
    sportSlug: 'basketball',
    badgeText: 'ELITE GRIP',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 26800,
    clicks: 2010,
    budget: 12500,
    isDeleted: false,
  },
  {
    title: 'ShotTracker 3D Court Vision Sensor System',
    sponsorName: 'ShotTracker Analytics',
    sponsorLogo: 'https://images.unsplash.com/photo-1576243345690-4e4b79b63288?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/shottracker-ai',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    tagline: 'Sub-centimeter shooting analytics, arc trajectory angles, and defensive spacing heat maps.',
    ctaText: 'View Analytics',
    sportSlug: 'basketball',
    badgeText: 'AI SHOOTING',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 18900,
    clicks: 1340,
    budget: 8200,
    isDeleted: false,
  },
  {
    title: 'NBA All-Star Courtside VIP Pass 2026',
    sponsorName: 'CourtSide Experiences',
    sponsorLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/nba-all-star',
    imageUrl: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800&auto=format&fit=crop&q=80',
    tagline: 'Floor-level seating, slam dunk contest lounge hospitality, and celebrity shootaround access.',
    ctaText: 'Get VIP Passes',
    sportSlug: 'basketball',
    badgeText: 'VIP COURTSIDE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 24300,
    clicks: 2100,
    budget: 15000,
    isDeleted: false,
  },

  // ==========================================
  // 5. TENNIS / ATP / WTA (5 Items)
  // ==========================================
  {
    title: 'Wilson Pro Staff v14 Precision Racket',
    sponsorName: 'Wilson Tennis Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/wilson-pro-staff',
    imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&auto=format&fit=crop&q=80',
    tagline: 'Braid 45 construction and Paradigm Bending for surgical baseline control and pinpoint court placement.',
    ctaText: 'Explore Pro Staff',
    sportSlug: 'tennis',
    badgeText: 'GRAND SLAM TECH',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 43000,
    clicks: 3750,
    budget: 21000,
    isDeleted: false,
  },
  {
    title: 'Babolat Pure Aero Rafa Origin',
    sponsorName: 'Babolat Sports',
    sponsorLogo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/babolat-rafa',
    imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&auto=format&fit=crop&q=80',
    tagline: 'Maximum rotational inertia and heavy topspin bite engineered to Rafa Nadal specifications.',
    ctaText: 'Shop Pure Aero',
    sportSlug: 'tennis',
    badgeText: 'RAFA EDITION',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 31200,
    clicks: 2490,
    budget: 16000,
    isDeleted: false,
  },
  {
    title: 'Head Speed MP Legend Auxetic 2.0',
    sponsorName: 'Head Tennis International',
    sponsorLogo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/head-speed',
    imageUrl: 'https://images.unsplash.com/photo-1530915534664-4ac642379740?w=800&auto=format&fit=crop&q=80',
    tagline: 'Sensational soft feel with explosive speed response trusted by top-seeded Novak Djokovic.',
    ctaText: 'Get 15% Off',
    sportSlug: 'tennis',
    badgeText: 'CHAMPIONS CHOICE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 21500,
    clicks: 1620,
    budget: 10500,
    isDeleted: false,
  },
  {
    title: 'Rolex Wimbledon Royal Box Hospitality',
    sponsorName: 'Rolex & Grand Slam Travel',
    sponsorLogo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/wimbledon-vip',
    imageUrl: 'https://images.unsplash.com/photo-1560089000-7433a4ebbd64?w=800&auto=format&fit=crop&q=80',
    tagline: 'Centre Court VIP debentures, champagne dining suites, and private chauffeured transfers in London.',
    ctaText: 'Inquire VIP Pass',
    sportSlug: 'tennis',
    badgeText: 'ROYAL VIP',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 19400,
    clicks: 1480,
    budget: 14000,
    isDeleted: false,
  },
  {
    title: 'Luxilon ALU Power 125 String Reel',
    sponsorName: 'Luxilon Strings Pro',
    sponsorLogo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/luxilon-alu',
    imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&auto=format&fit=crop&q=80',
    tagline: 'The #1 co-polyester string choice across the ATP & WTA tour for ultimate durability and control.',
    ctaText: 'Order String Reel',
    sportSlug: 'tennis',
    badgeText: 'PRO TOUR CHOICE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 14800,
    clicks: 1120,
    budget: 6500,
    isDeleted: false,
  },

  // ==========================================
  // 6. BASEBALL / MLB (5 Items)
  // ==========================================
  {
    title: 'Rawlings Pro Preferred Kip Skin Glove',
    sponsorName: 'Rawlings Baseball Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1508802959524-4157ac38e3cb?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/rawlings-pro',
    imageUrl: 'https://images.unsplash.com/photo-1508802959524-4157ac38e3cb?w=800&auto=format&fit=crop&q=80',
    tagline: 'Flawless full-grain kip skin leather crafted for Gold Glove winning infield and outfield defensive mastery.',
    ctaText: 'Customize Glove',
    sportSlug: 'baseball',
    badgeText: 'GOLD GLOVE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 39500,
    clicks: 3410,
    budget: 20000,
    isDeleted: false,
  },
  {
    title: 'Louisville Slugger Prime Bone-Rubbed Maple',
    sponsorName: 'Louisville Slugger Co.',
    sponsorLogo: 'https://images.unsplash.com/photo-1508802959524-4157ac38e3cb?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/slugger-maple',
    imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&auto=format&fit=crop&q=80',
    tagline: 'Pro-certified bone-rubbed maple bat providing maximum exit velocity and immense home run pop.',
    ctaText: 'Shop Prime Bat',
    sportSlug: 'baseball',
    badgeText: 'MLB APPROVED',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 28400,
    clicks: 2210,
    budget: 14500,
    isDeleted: false,
  },
  {
    title: 'Rapsodo Pitch 3.0 Telemetry AI',
    sponsorName: 'Rapsodo Diamond Tech',
    sponsorLogo: 'https://images.unsplash.com/photo-1576243345690-4e4b79b63288?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/rapsodo-pitch',
    imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&auto=format&fit=crop&q=80',
    tagline: 'Track spin efficiency, true vertical pitch break, gyro spin axis, and 3D strike zone trajectory.',
    ctaText: 'View Sensor Data',
    sportSlug: 'baseball',
    badgeText: 'PITCH ANALYTICS',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 19200,
    clicks: 1450,
    budget: 9500,
    isDeleted: false,
  },
  {
    title: 'New Era 59FIFTY Authentic MLB Caps',
    sponsorName: 'New Era Cap Co.',
    sponsorLogo: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/new-era-mlb',
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
    tagline: 'The official on-field fitted caps worn by all 30 Major League Baseball franchises.',
    ctaText: 'Find Your Team',
    sportSlug: 'baseball',
    badgeText: 'OFFICIAL HEADWEAR',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 25100,
    clicks: 2190,
    budget: 11000,
    isDeleted: false,
  },
  {
    title: 'MLB World Series Dugout Club Pass 2026',
    sponsorName: 'Diamond VIP Hospitality',
    sponsorLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/world-series-vip',
    imageUrl: 'https://images.unsplash.com/photo-1508802959524-4157ac38e3cb?w=800&auto=format&fit=crop&q=80',
    tagline: 'Behind-the-plate VIP club passes, batting practice field access, and legendary player receptions.',
    ctaText: 'Book Series Pass',
    sportSlug: 'baseball',
    badgeText: 'WORLD SERIES VIP',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 17600,
    clicks: 1520,
    budget: 12000,
    isDeleted: false,
  },

  // ==========================================
  // 7. HOCKEY / NHL (5 Items)
  // ==========================================
  {
    title: 'Bauer Supreme Shadow Composite Stick',
    sponsorName: 'Bauer Hockey Global',
    sponsorLogo: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'homepage_hero',
    targetUrl: 'https://goalmills.com/partners/bauer-supreme',
    imageUrl: 'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800&auto=format&fit=crop&q=80',
    tagline: 'Sonic Core blade technology with TeXtreme carbon weave for explosive 100mph+ slap shots.',
    ctaText: 'Get Supreme Stick',
    sportSlug: 'hockey',
    badgeText: 'NHL PRO GEAR',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 10,
    impressions: 37200,
    clicks: 3180,
    budget: 19000,
    isDeleted: false,
  },
  {
    title: 'CCM JetSpeed FT6 Pro Ice Skates',
    sponsorName: 'CCM Hockey',
    sponsorLogo: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=120&auto=format&fit=crop&q=80',
    type: 'banner',
    placement: 'sports_pulse',
    targetUrl: 'https://goalmills.com/partners/ccm-jetspeed',
    imageUrl: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=800&auto=format&fit=crop&q=80',
    tagline: 'One-piece boot power with Step Blacksteel runners for unmatched acceleration and sharp crossovers.',
    ctaText: 'Shop FT6 Pro',
    sportSlug: 'hockey',
    badgeText: 'PRO STRIDE',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 8,
    impressions: 26500,
    clicks: 2110,
    budget: 13500,
    isDeleted: false,
  },
  {
    title: 'Warrior Covert QR5 Pro Impact Shield Armor',
    sponsorName: 'Warrior Sports Hockey',
    sponsorLogo: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=120&auto=format&fit=crop&q=80',
    type: 'match_card',
    placement: 'match_details',
    targetUrl: 'https://goalmills.com/partners/warrior-covert',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    tagline: 'AxyFlex spine shielding and ultra-light foam padding providing 360-degree impact deflection.',
    ctaText: 'Explore Armor',
    sportSlug: 'hockey',
    badgeText: 'MAX PROTECTION',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 6,
    impressions: 18100,
    clicks: 1390,
    budget: 8900,
    isDeleted: false,
  },
  {
    title: 'NHL Winter Classic VIP Glass Access',
    sponsorName: 'NHL Experiences Pro',
    sponsorLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    type: 'article_header',
    placement: 'global_sidebar',
    targetUrl: 'https://goalmills.com/partners/winter-classic-vip',
    imageUrl: 'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800&auto=format&fit=crop&q=80',
    tagline: 'Outdoor rink-side heated glass seating, alumni dinner, and official commemorative game pucks.',
    ctaText: 'Book Classic Seats',
    sportSlug: 'hockey',
    badgeText: 'WINTER CLASSIC',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 4,
    impressions: 22800,
    clicks: 1970,
    budget: 11500,
    isDeleted: false,
  },
  {
    title: 'Howies Pro Hockey Cloth Tape & Wax Bundle',
    sponsorName: 'Howies Hockey Tape',
    sponsorLogo: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=120&auto=format&fit=crop&q=80',
    type: 'newsletter_sponsor',
    placement: 'newsletter_footer',
    targetUrl: 'https://goalmills.com/partners/howies-tape',
    imageUrl: 'https://images.unsplash.com/photo-1515703407324-5f753eed8597?w=800&auto=format&fit=crop&q=80',
    tagline: 'High-thread count adhesive cloth tape and strawberry-scented stick wax used in all 32 NHL locker rooms.',
    ctaText: 'Stock Up Bundle',
    sportSlug: 'hockey',
    badgeText: 'LOCKER ROOM ESSENTIAL',
    status: 'active',
    startDate: new Date('2026-01-01'),
    priority: 2,
    impressions: 15200,
    clicks: 1210,
    budget: 5500,
    isDeleted: false,
  },
];

async function seedSponsorships() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URL as string);
    console.log('Connected to MongoDB successfully.');

    console.log('Clearing existing active and test sponsorships...');
    await Sponsorship.deleteMany({});

    console.log(`Inserting ${SPONSORSHIPS_DATA.length} sponsorship records across 7 categories (5 per category)...`);
    const inserted = await Sponsorship.insertMany(SPONSORSHIPS_DATA);
    console.log(`Successfully seeded ${inserted.length} sponsorships into the database!`);

    // Log summary per sport category
    const counts = inserted.reduce((acc: Record<string, number>, s) => {
      acc[s.sportSlug] = (acc[s.sportSlug] || 0) + 1;
      return acc;
    }, {});
    console.log('Category breakdown:', counts);

    await mongoose.disconnect();
    console.log('MongoDB connection closed.');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding sponsorships:', error);
    process.exit(1);
  }
}

seedSponsorships();
