version: '3.8'

services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goalmills-mailer
    restart: unless-stopped
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - PORT=8085
      - TZ=Africa/Lagos
