import { AfricaPriorityEntry } from '@goalmills/types';

export const AFRICA_PRIORITY_REGISTRY: AfricaPriorityEntry[] = [
  {
    countryCode: 'CAF',
    countryName: 'Africa',
    competitionId: 'CAF-AFCON',
    competitionName: 'Africa Cup of Nations',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 1,
    providerId: 6,
    isActive: true,
  },
  {
    countryCode: 'CAF',
    countryName: 'Africa',
    competitionId: 'CAF-CHAMPIONS-LEAGUE',
    competitionName: 'CAF Champions League',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 2,
    providerId: 19,
    isActive: true,
  },
  {
    countryCode: 'CAF',
    countryName: 'Africa',
    competitionId: 'CAF-CONFEDERATION-CUP',
    competitionName: 'CAF Confederation Cup',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 3,
    providerId: 20,
    isActive: true,
  },
  {
    countryCode: 'CAF',
    countryName: 'Africa',
    competitionId: 'CAF-CHAN',
    competitionName: 'African Nations Championship (CHAN)',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 4,
    providerId: 360,
    isActive: true,
  },
  {
    countryCode: 'CAF',
    countryName: 'Africa',
    competitionId: 'CAF-WAFCON',
    competitionName: "Women's Africa Cup of Nations (WAFCON)",
    tier: 1,
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    priorityRank: 5,
    providerId: 365,
    isActive: true,
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    competitionId: 'NGA-NPFL',
    competitionName: 'Nigeria Premier Football League (NPFL)',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 6,
    providerId: 247,
    isActive: true,
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    competitionId: 'ZAF-PSL',
    competitionName: 'Betway Premiership (PSL)',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 7,
    providerId: 288,
    isActive: true,
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    competitionId: 'EGY-PREMIER-LEAGUE',
    competitionName: 'Egyptian Premier League',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 8,
    providerId: 178,
    isActive: true,
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    competitionId: 'MAR-BOTOLA-PRO',
    competitionName: 'Botola Pro Inwi',
    tier: 1,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 9,
    providerId: 233,
    isActive: true,
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    competitionId: 'GHA-PREMIER-LEAGUE',
    competitionName: 'Ghana Premier League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 10,
    providerId: 198,
    isActive: true,
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    competitionId: 'DZA-LIGUE-1',
    competitionName: 'Ligue 1 Mobilis',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 11,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    competitionId: 'TUN-LIGUE-1',
    competitionName: 'Ligue Professionnelle 1',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 12,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    competitionId: 'TZA-PREMIER-LEAGUE',
    competitionName: 'Tanzanian Premier League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 13,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'CD',
    countryName: 'DR Congo',
    competitionId: 'COD-LINAFOOT',
    competitionName: 'Linafoot',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 14,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'CI',
    countryName: 'Ivory Coast',
    competitionId: 'CIV-LIGUE-1',
    competitionName: 'Ligue 1 (CIV)',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 15,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    competitionId: 'ZMB-SUPER-LEAGUE',
    competitionName: 'Zambia Super League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 16,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    competitionId: 'KEN-PREMIER-LEAGUE',
    competitionName: 'FKF Premier League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 17,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    competitionId: 'AGO-GIRABOLA',
    competitionName: 'Girabola',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 18,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    competitionId: 'UGA-PREMIER-LEAGUE',
    competitionName: 'Uganda Premier League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 19,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'SD',
    countryName: 'Sudan',
    competitionId: 'SDN-PREMIER-LEAGUE',
    competitionName: 'Sudan Premier League',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 20,
    providerId: 0,
    isActive: true,
  },
  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    competitionId: 'CMR-ELITE-ONE',
    competitionName: 'Cameroon Elite One',
    tier: 2,
    gender: 'MALE',
    ageCategory: 'SENIOR',
    priorityRank: 21,
    providerId: 0,
    isActive: true,
  },
];

export function getAfricaPriorityEntries(): AfricaPriorityEntry[] {
  return [...AFRICA_PRIORITY_REGISTRY].sort((a, b) => a.priorityRank - b.priorityRank);
}

export function getAfricaDomesticLeagues(): AfricaPriorityEntry[] {
  return AFRICA_PRIORITY_REGISTRY.filter((entry) => entry.countryCode !== 'CAF').sort(
    (a, b) => a.priorityRank - b.priorityRank
  );
}

export function getAfricanCountries(): AfricaPriorityEntry[] {
  return getAfricaDomesticLeagues();
}
