import { PriorityClub } from '@goalmills/types';

export const TEAM_LOGO_BASE = 'https://media.api-sports.io/football/teams';
export const teamLogo = (apiSportsTeamId: number): string =>
  `${TEAM_LOGO_BASE}/${apiSportsTeamId}.png`;

export const PRIORITY_CLUBS: Record<string, PriorityClub> = {
  // ─── Premier League ─────────────────────────────────────────────────────────
  arsenal: {
    id: 'arsenal',
    providerId: '42',
    providerName: 'allsportsapi',
    name: 'Arsenal',
    shortName: 'Arsenal',
    slug: 'arsenal',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(42),
    stadium: 'Emirates Stadium',
    founded: 1886,
    globalRank: 3,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 1,
  },
  'manchester-city': {
    id: 'manchester-city',
    providerId: '50',
    providerName: 'allsportsapi',
    name: 'Manchester City',
    shortName: 'Man City',
    slug: 'manchester-city',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(50),
    stadium: 'Etihad Stadium',
    founded: 1880,
    globalRank: 1,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 2,
  },
  liverpool: {
    id: 'liverpool',
    providerId: '40',
    providerName: 'allsportsapi',
    name: 'Liverpool',
    shortName: 'Liverpool',
    slug: 'liverpool',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(40),
    stadium: 'Anfield',
    founded: 1892,
    globalRank: 4,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 3,
  },
  chelsea: {
    id: 'chelsea',
    providerId: '49',
    providerName: 'allsportsapi',
    name: 'Chelsea',
    shortName: 'Chelsea',
    slug: 'chelsea',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(49),
    stadium: 'Stamford Bridge',
    founded: 1905,
    globalRank: 7,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 4,
  },
  'manchester-united': {
    id: 'manchester-united',
    providerId: '33',
    providerName: 'allsportsapi',
    name: 'Manchester United',
    shortName: 'Man United',
    slug: 'manchester-united',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(33),
    stadium: 'Old Trafford',
    founded: 1878,
    globalRank: 8,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 5,
  },
  tottenham: {
    id: 'tottenham',
    providerId: '47',
    providerName: 'allsportsapi',
    name: 'Tottenham Hotspur',
    shortName: 'Spurs',
    slug: 'tottenham',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(47),
    stadium: 'Tottenham Hotspur Stadium',
    founded: 1882,
    globalRank: 12,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 6,
  },
  'aston-villa': {
    id: 'aston-villa',
    providerId: '66',
    providerName: 'allsportsapi',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    slug: 'aston-villa',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(66),
    stadium: 'Villa Park',
    founded: 1874,
    globalRank: 14,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 7,
  },
  'newcastle-united': {
    id: 'newcastle-united',
    providerId: '34',
    providerName: 'allsportsapi',
    name: 'Newcastle United',
    shortName: 'Newcastle',
    slug: 'newcastle-united',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(34),
    stadium: "St. James' Park",
    founded: 1892,
    globalRank: 16,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 8,
  },

  // ─── La Liga ────────────────────────────────────────────────────────────────
  'real-madrid': {
    id: 'real-madrid',
    providerId: '541',
    providerName: 'allsportsapi',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    slug: 'real-madrid',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(541),
    stadium: 'Santiago Bernabéu',
    founded: 1902,
    globalRank: 2,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 9,
  },
  barcelona: {
    id: 'barcelona',
    providerId: '529',
    providerName: 'allsportsapi',
    name: 'FC Barcelona',
    shortName: 'Barcelona',
    slug: 'barcelona',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(529),
    stadium: 'Spotify Camp Nou',
    founded: 1899,
    globalRank: 5,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 10,
  },
  'atletico-madrid': {
    id: 'atletico-madrid',
    providerId: '530',
    providerName: 'allsportsapi',
    name: 'Atlético Madrid',
    shortName: 'Atlético',
    slug: 'atletico-madrid',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(530),
    stadium: 'Riyadh Air Metropolitano',
    founded: 1903,
    globalRank: 10,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 11,
  },

  // ─── Serie A ────────────────────────────────────────────────────────────────
  inter: {
    id: 'inter',
    providerId: '505',
    providerName: 'allsportsapi',
    name: 'Inter Milan',
    shortName: 'Inter',
    slug: 'inter',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(505),
    stadium: 'San Siro',
    founded: 1908,
    globalRank: 6,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 12,
  },
  juventus: {
    id: 'juventus',
    providerId: '496',
    providerName: 'allsportsapi',
    name: 'Juventus',
    shortName: 'Juventus',
    slug: 'juventus',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(496),
    stadium: 'Allianz Stadium',
    founded: 1897,
    globalRank: 11,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 13,
  },
  milan: {
    id: 'milan',
    providerId: '489',
    providerName: 'allsportsapi',
    name: 'AC Milan',
    shortName: 'Milan',
    slug: 'milan',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(489),
    stadium: 'San Siro',
    founded: 1899,
    globalRank: 13,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 14,
  },
  napoli: {
    id: 'napoli',
    providerId: '492',
    providerName: 'allsportsapi',
    name: 'Napoli',
    shortName: 'Napoli',
    slug: 'napoli',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(492),
    stadium: 'Stadio Diego Armando Maradona',
    founded: 1926,
    globalRank: 15,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 15,
  },

  // ─── Bundesliga ─────────────────────────────────────────────────────────────
  'bayern-munich': {
    id: 'bayern-munich',
    providerId: '157',
    providerName: 'allsportsapi',
    name: 'Bayern Munich',
    shortName: 'Bayern',
    slug: 'bayern-munich',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(157),
    stadium: 'Allianz Arena',
    founded: 1900,
    globalRank: 9,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 16,
  },
  'bayer-leverkusen': {
    id: 'bayer-leverkusen',
    providerId: '168',
    providerName: 'allsportsapi',
    name: 'Bayer Leverkusen',
    shortName: 'Leverkusen',
    slug: 'bayer-leverkusen',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(168),
    stadium: 'BayArena',
    founded: 1904,
    globalRank: 17,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 17,
  },
  'borussia-dortmund': {
    id: 'borussia-dortmund',
    providerId: '165',
    providerName: 'allsportsapi',
    name: 'Borussia Dortmund',
    shortName: 'Dortmund',
    slug: 'borussia-dortmund',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(165),
    stadium: 'Signal Iduna Park',
    founded: 1909,
    globalRank: 18,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 18,
  },

  // ─── Ligue 1 ────────────────────────────────────────────────────────────────
  'paris-saint-germain': {
    id: 'paris-saint-germain',
    providerId: '85',
    providerName: 'allsportsapi',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    slug: 'paris-saint-germain',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(85),
    stadium: 'Parc des Princes',
    founded: 1970,
    globalRank: 19,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 19,
  },
  marseille: {
    id: 'marseille',
    providerId: '81',
    providerName: 'allsportsapi',
    name: 'Olympique de Marseille',
    shortName: 'Marseille',
    slug: 'marseille',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(81),
    stadium: 'Stade Vélodrome',
    founded: 1899,
    globalRank: 25,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 20,
  },

  // ─── African Giants (Africa Priority) ───────────────────────────────────────
  'al-ahly': {
    id: 'al-ahly',
    providerId: '1029',
    providerName: 'allsportsapi',
    name: 'Al Ahly SC',
    shortName: 'Al Ahly',
    slug: 'al-ahly',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1029),
    stadium: 'Cairo International Stadium',
    founded: 1907,
    globalRank: 30,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 21,
  },
  zamalek: {
    id: 'zamalek',
    providerId: '1030',
    providerName: 'allsportsapi',
    name: 'Zamalek SC',
    shortName: 'Zamalek',
    slug: 'zamalek',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1030),
    stadium: 'Cairo International Stadium',
    founded: 1911,
    globalRank: 35,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 22,
  },
  'mamelodi-sundowns': {
    id: 'mamelodi-sundowns',
    providerId: '1047',
    providerName: 'allsportsapi',
    name: 'Mamelodi Sundowns',
    shortName: 'Sundowns',
    slug: 'mamelodi-sundowns',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1047),
    stadium: 'Loftus Versfeld Stadium',
    founded: 1970,
    globalRank: 32,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 23,
  },
  'orlando-pirates': {
    id: 'orlando-pirates',
    providerId: '1049',
    providerName: 'allsportsapi',
    name: 'Orlando Pirates',
    shortName: 'Pirates',
    slug: 'orlando-pirates',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1049),
    stadium: 'Orlando Stadium',
    founded: 1937,
    globalRank: 38,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 24,
  },
  'kaizer-chiefs': {
    id: 'kaizer-chiefs',
    providerId: '1048',
    providerName: 'allsportsapi',
    name: 'Kaizer Chiefs',
    shortName: 'Kaizer Chiefs',
    slug: 'kaizer-chiefs',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1048),
    stadium: 'FNB Stadium',
    founded: 1970,
    globalRank: 40,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 25,
  },
  'wydad-casablanca': {
    id: 'wydad-casablanca',
    providerId: '1034',
    providerName: 'allsportsapi',
    name: 'Wydad AC Casablanca',
    shortName: 'Wydad',
    slug: 'wydad-casablanca',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1034),
    stadium: 'Stade Mohammed V',
    founded: 1937,
    globalRank: 36,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 26,
  },
  'raja-casablanca': {
    id: 'raja-casablanca',
    providerId: '1035',
    providerName: 'allsportsapi',
    name: 'Raja Club Athletic',
    shortName: 'Raja',
    slug: 'raja-casablanca',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1035),
    stadium: 'Stade Mohammed V',
    founded: 1949,
    globalRank: 37,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 27,
  },
  'esperance-de-tunis': {
    id: 'esperance-de-tunis',
    providerId: '1038',
    providerName: 'allsportsapi',
    name: 'Espérance Sportive de Tunis',
    shortName: 'Espérance',
    slug: 'esperance-de-tunis',
    competitionId: 'TUN-LIGUE-1',
    countryCode: 'TN',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1038),
    stadium: 'Stade Hammadi Agrebi',
    founded: 1919,
    globalRank: 39,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 28,
  },
  'tp-mazembe': {
    id: 'tp-mazembe',
    providerId: '1041',
    providerName: 'allsportsapi',
    name: 'TP Mazembe',
    shortName: 'TP Mazembe',
    slug: 'tp-mazembe',
    competitionId: 'COD-LINAFOOT',
    countryCode: 'CD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1041),
    stadium: 'Stade TP Mazembe',
    founded: 1939,
    globalRank: 42,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 29,
  },
  'enyimba-fc': {
    id: 'enyimba-fc',
    providerId: '1043',
    providerName: 'allsportsapi',
    name: 'Enyimba International FC',
    shortName: 'Enyimba',
    slug: 'enyimba-fc',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1043),
    stadium: 'Enyimba International Stadium',
    founded: 1976,
    globalRank: 45,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 30,
  },
  'remo-stars': {
    id: 'remo-stars',
    providerId: '1044',
    providerName: 'allsportsapi',
    name: 'Remo Stars FC',
    shortName: 'Remo Stars',
    slug: 'remo-stars',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1044),
    stadium: 'Remo Stars Stadium, Ikenne',
    founded: 2010,
    globalRank: 50,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 31,
  },
  'rangers-international': {
    id: 'rangers-international',
    providerId: '1045',
    providerName: 'allsportsapi',
    name: 'Rangers International FC',
    shortName: 'Rangers',
    slug: 'rangers-international',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1045),
    stadium: 'Nnamdi Azikiwe Stadium',
    founded: 1970,
    globalRank: 52,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 12,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 32,
  },
  'rivers-united': {
    id: 'rivers-united',
    providerId: '1046',
    providerName: 'allsportsapi',
    name: 'Rivers United FC',
    shortName: 'Rivers United',
    slug: 'rivers-united',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1046),
    stadium: 'Adokiye Amiesimaka Stadium',
    founded: 2016,
    globalRank: 55,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 13,
    isFeatured: false,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 33,
  },
  'asante-kotoko': {
    id: 'asante-kotoko',
    providerId: '1050',
    providerName: 'allsportsapi',
    name: 'Asante Kotoko SC',
    shortName: 'Kotoko',
    slug: 'asante-kotoko',
    competitionId: 'GHA-PREMIER-LEAGUE',
    countryCode: 'GH',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1050),
    stadium: 'Baba Yara Stadium',
    founded: 1935,
    globalRank: 58,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 14,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 34,
  },
  'hearts-of-oak': {
    id: 'hearts-of-oak',
    providerId: '1051',
    providerName: 'allsportsapi',
    name: 'Hearts of Oak SC',
    shortName: 'Hearts of Oak',
    slug: 'hearts-of-oak',
    competitionId: 'GHA-PREMIER-LEAGUE',
    countryCode: 'GH',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1051),
    stadium: 'Accra Sports Stadium',
    founded: 1911,
    globalRank: 60,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 15,
    isFeatured: false,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 35,
  },
  'simba-sc': {
    id: 'simba-sc',
    providerId: '1052',
    providerName: 'allsportsapi',
    name: 'Simba SC',
    shortName: 'Simba',
    slug: 'simba-sc',
    competitionId: 'TZA-PREMIER-LEAGUE',
    countryCode: 'TZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1052),
    stadium: 'Benjamin Mkapa Stadium',
    founded: 1936,
    globalRank: 48,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 16,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 36,
  },
  'young-africans': {
    id: 'young-africans',
    providerId: '1053',
    providerName: 'allsportsapi',
    name: 'Young Africans SC (Yanga)',
    shortName: 'Yanga',
    slug: 'young-africans',
    competitionId: 'TZA-PREMIER-LEAGUE',
    countryCode: 'TZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1053),
    stadium: 'Benjamin Mkapa Stadium',
    founded: 1935,
    globalRank: 49,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 17,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 37,
  },

  // ─── Saudi Pro League & Americas ───────────────────────────────────────────
  'al-hilal': {
    id: 'al-hilal',
    providerId: '2939',
    providerName: 'allsportsapi',
    name: 'Al-Hilal SFC',
    shortName: 'Al Hilal',
    slug: 'al-hilal',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2939),
    stadium: 'Kingdom Arena',
    founded: 1957,
    globalRank: 22,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 38,
  },
  'al-nassr': {
    id: 'al-nassr',
    providerId: '2938',
    providerName: 'allsportsapi',
    name: 'Al-Nassr FC',
    shortName: 'Al Nassr',
    slug: 'al-nassr',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2938),
    stadium: 'Al-Awwal Park',
    founded: 1955,
    globalRank: 24,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 39,
  },
  'inter-miami': {
    id: 'inter-miami',
    providerId: '9568',
    providerName: 'allsportsapi',
    name: 'Inter Miami CF',
    shortName: 'Inter Miami',
    slug: 'inter-miami',
    competitionId: 'USA-MLS',
    countryCode: 'US',
    confederationCode: 'CONCACAF',
    logoUrl: teamLogo(9568),
    stadium: 'Chase Stadium',
    founded: 2018,
    globalRank: 28,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 40,
  },
};

export const PRIORITY_CLUBS_LIST: PriorityClub[] = Object.values(PRIORITY_CLUBS).sort(
  (a, b) => a.priorityRank - b.priorityRank
);

const CLUB_SLUG_MAP = new Map<string, PriorityClub>();
for (const club of PRIORITY_CLUBS_LIST) {
  CLUB_SLUG_MAP.set(club.slug.toLowerCase(), club);
  CLUB_SLUG_MAP.set(club.id.toLowerCase(), club);
}

export function getPriorityClub(idOrSlug: string): PriorityClub | undefined {
  if (!idOrSlug) return undefined;
  return CLUB_SLUG_MAP.get(idOrSlug.trim().toLowerCase());
}

export function getClubsByCompetition(compCanonicalIdOrSlug: string): PriorityClub[] {
  const norm = compCanonicalIdOrSlug.trim().toLowerCase();
  return PRIORITY_CLUBS_LIST.filter(
    (c) => c.competitionId.toLowerCase() === norm || c.competitionId.toLowerCase().includes(norm)
  );
}

export function getClubsByCountry(countryCode: string): PriorityClub[] {
  const code = countryCode.toUpperCase();
  return PRIORITY_CLUBS_LIST.filter((c) => c.countryCode === code);
}

export function getAfricanClubs(): PriorityClub[] {
  return PRIORITY_CLUBS_LIST.filter((c) => c.isAfrican);
}

export function getFeaturedClubs(): PriorityClub[] {
  return PRIORITY_CLUBS_LIST.filter((c) => c.isFeatured);
}
