import { PriorityClub } from '@goalmills/types';

export const TEAM_LOGO_BASE = 'https://media.api-sports.io/football/teams';
export const teamLogo = (apiSportsTeamId: number): string =>
  `${TEAM_LOGO_BASE}/${apiSportsTeamId}.png`;

export const PRIORITY_CLUBS: Record<string, PriorityClub> = {
  // ─── Premier League ─────────────────────────────────────────────────────────
  arsenal: {
    id: 'arsenal',
    providerId: '42',
    providerName: 'allsportsapi',
    name: 'Arsenal',
    shortName: 'Arsenal',
    slug: 'arsenal',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(42),
    stadium: 'Emirates Stadium',
    founded: 1886,
    globalRank: 3,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 1,
  },
  'manchester-city': {
    id: 'manchester-city',
    providerId: '50',
    providerName: 'allsportsapi',
    name: 'Manchester City',
    shortName: 'Man City',
    slug: 'manchester-city',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(50),
    stadium: 'Etihad Stadium',
    founded: 1880,
    globalRank: 1,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 2,
  },
  liverpool: {
    id: 'liverpool',
    providerId: '40',
    providerName: 'allsportsapi',
    name: 'Liverpool',
    shortName: 'Liverpool',
    slug: 'liverpool',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(40),
    stadium: 'Anfield',
    founded: 1892,
    globalRank: 4,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 3,
  },
  chelsea: {
    id: 'chelsea',
    providerId: '49',
    providerName: 'allsportsapi',
    name: 'Chelsea',
    shortName: 'Chelsea',
    slug: 'chelsea',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(49),
    stadium: 'Stamford Bridge',
    founded: 1905,
    globalRank: 7,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 4,
  },
  'manchester-united': {
    id: 'manchester-united',
    providerId: '33',
    providerName: 'allsportsapi',
    name: 'Manchester United',
    shortName: 'Man United',
    slug: 'manchester-united',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(33),
    stadium: 'Old Trafford',
    founded: 1878,
    globalRank: 8,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 5,
  },
  tottenham: {
    id: 'tottenham',
    providerId: '47',
    providerName: 'allsportsapi',
    name: 'Tottenham Hotspur',
    shortName: 'Spurs',
    slug: 'tottenham',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(47),
    stadium: 'Tottenham Hotspur Stadium',
    founded: 1882,
    globalRank: 12,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 6,
  },
  'aston-villa': {
    id: 'aston-villa',
    providerId: '66',
    providerName: 'allsportsapi',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    slug: 'aston-villa',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(66),
    stadium: 'Villa Park',
    founded: 1874,
    globalRank: 14,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 7,
  },
  'newcastle-united': {
    id: 'newcastle-united',
    providerId: '34',
    providerName: 'allsportsapi',
    name: 'Newcastle United',
    shortName: 'Newcastle',
    slug: 'newcastle-united',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(34),
    stadium: "St. James' Park",
    founded: 1892,
    globalRank: 16,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 8,
  },

  // ─── La Liga ────────────────────────────────────────────────────────────────
  'real-madrid': {
    id: 'real-madrid',
    providerId: '541',
    providerName: 'allsportsapi',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    slug: 'real-madrid',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(541),
    stadium: 'Santiago Bernabéu',
    founded: 1902,
    globalRank: 2,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 9,
  },
  barcelona: {
    id: 'barcelona',
    providerId: '529',
    providerName: 'allsportsapi',
    name: 'FC Barcelona',
    shortName: 'Barcelona',
    slug: 'barcelona',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(529),
    stadium: 'Spotify Camp Nou',
    founded: 1899,
    globalRank: 5,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 10,
  },
  'atletico-madrid': {
    id: 'atletico-madrid',
    providerId: '530',
    providerName: 'allsportsapi',
    name: 'Atlético Madrid',
    shortName: 'Atlético',
    slug: 'atletico-madrid',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(530),
    stadium: 'Riyadh Air Metropolitano',
    founded: 1903,
    globalRank: 10,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 11,
  },

  // ─── Serie A ────────────────────────────────────────────────────────────────
  inter: {
    id: 'inter',
    providerId: '505',
    providerName: 'allsportsapi',
    name: 'Inter Milan',
    shortName: 'Inter',
    slug: 'inter',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(505),
    stadium: 'San Siro',
    founded: 1908,
    globalRank: 6,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 12,
  },
  juventus: {
    id: 'juventus',
    providerId: '496',
    providerName: 'allsportsapi',
    name: 'Juventus',
    shortName: 'Juventus',
    slug: 'juventus',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(496),
    stadium: 'Allianz Stadium',
    founded: 1897,
    globalRank: 11,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 13,
  },
  milan: {
    id: 'milan',
    providerId: '489',
    providerName: 'allsportsapi',
    name: 'AC Milan',
    shortName: 'Milan',
    slug: 'milan',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(489),
    stadium: 'San Siro',
    founded: 1899,
    globalRank: 13,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 14,
  },
  napoli: {
    id: 'napoli',
    providerId: '492',
    providerName: 'allsportsapi',
    name: 'Napoli',
    shortName: 'Napoli',
    slug: 'napoli',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(492),
    stadium: 'Stadio Diego Armando Maradona',
    founded: 1926,
    globalRank: 15,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 15,
  },

  // ─── Bundesliga ─────────────────────────────────────────────────────────────
  'bayern-munich': {
    id: 'bayern-munich',
    providerId: '157',
    providerName: 'allsportsapi',
    name: 'Bayern Munich',
    shortName: 'Bayern',
    slug: 'bayern-munich',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(157),
    stadium: 'Allianz Arena',
    founded: 1900,
    globalRank: 9,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 16,
  },
  'bayer-leverkusen': {
    id: 'bayer-leverkusen',
    providerId: '168',
    providerName: 'allsportsapi',
    name: 'Bayer Leverkusen',
    shortName: 'Leverkusen',
    slug: 'bayer-leverkusen',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(168),
    stadium: 'BayArena',
    founded: 1904,
    globalRank: 17,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 17,
  },
  'borussia-dortmund': {
    id: 'borussia-dortmund',
    providerId: '165',
    providerName: 'allsportsapi',
    name: 'Borussia Dortmund',
    shortName: 'Dortmund',
    slug: 'borussia-dortmund',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(165),
    stadium: 'Signal Iduna Park',
    founded: 1909,
    globalRank: 18,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 18,
  },

  // ─── Ligue 1 ────────────────────────────────────────────────────────────────
  'paris-saint-germain': {
    id: 'paris-saint-germain',
    providerId: '85',
    providerName: 'allsportsapi',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    slug: 'paris-saint-germain',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(85),
    stadium: 'Parc des Princes',
    founded: 1970,
    globalRank: 19,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 19,
  },
  marseille: {
    id: 'marseille',
    providerId: '81',
    providerName: 'allsportsapi',
    name: 'Olympique de Marseille',
    shortName: 'Marseille',
    slug: 'marseille',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(81),
    stadium: 'Stade Vélodrome',
    founded: 1899,
    globalRank: 25,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: false,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 20,
  },

  // ─── African Giants (Africa Priority) ───────────────────────────────────────
  'al-ahly': {
    id: 'al-ahly',
    providerId: '1029',
    providerName: 'allsportsapi',
    name: 'Al Ahly SC',
    shortName: 'Al Ahly',
    slug: 'al-ahly',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1029),
    stadium: 'Cairo International Stadium',
    founded: 1907,
    globalRank: 30,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 21,
  },
  zamalek: {
    id: 'zamalek',
    providerId: '1030',
    providerName: 'allsportsapi',
    name: 'Zamalek SC',
    shortName: 'Zamalek',
    slug: 'zamalek',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1030),
    stadium: 'Cairo International Stadium',
    founded: 1911,
    globalRank: 35,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 22,
  },
  'mamelodi-sundowns': {
    id: 'mamelodi-sundowns',
    providerId: '1047',
    providerName: 'allsportsapi',
    name: 'Mamelodi Sundowns',
    shortName: 'Sundowns',
    slug: 'mamelodi-sundowns',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1047),
    stadium: 'Loftus Versfeld Stadium',
    founded: 1970,
    globalRank: 32,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 23,
  },
  'orlando-pirates': {
    id: 'orlando-pirates',
    providerId: '1049',
    providerName: 'allsportsapi',
    name: 'Orlando Pirates',
    shortName: 'Pirates',
    slug: 'orlando-pirates',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1049),
    stadium: 'Orlando Stadium',
    founded: 1937,
    globalRank: 38,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 24,
  },
  'kaizer-chiefs': {
    id: 'kaizer-chiefs',
    providerId: '1048',
    providerName: 'allsportsapi',
    name: 'Kaizer Chiefs',
    shortName: 'Kaizer Chiefs',
    slug: 'kaizer-chiefs',
    competitionId: 'ZAF-PSL',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1048),
    stadium: 'FNB Stadium',
    founded: 1970,
    globalRank: 40,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 25,
  },
  'wydad-casablanca': {
    id: 'wydad-casablanca',
    providerId: '1034',
    providerName: 'allsportsapi',
    name: 'Wydad AC Casablanca',
    shortName: 'Wydad',
    slug: 'wydad-casablanca',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1034),
    stadium: 'Stade Mohammed V',
    founded: 1937,
    globalRank: 36,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 26,
  },
  'raja-casablanca': {
    id: 'raja-casablanca',
    providerId: '1035',
    providerName: 'allsportsapi',
    name: 'Raja Club Athletic',
    shortName: 'Raja',
    slug: 'raja-casablanca',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1035),
    stadium: 'Stade Mohammed V',
    founded: 1949,
    globalRank: 37,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 27,
  },
  'esperance-de-tunis': {
    id: 'esperance-de-tunis',
    providerId: '1038',
    providerName: 'allsportsapi',
    name: 'Espérance Sportive de Tunis',
    shortName: 'Espérance',
    slug: 'esperance-de-tunis',
    competitionId: 'TUN-LIGUE-1',
    countryCode: 'TN',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1038),
    stadium: 'Stade Hammadi Agrebi',
    founded: 1919,
    globalRank: 39,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 28,
  },
  'tp-mazembe': {
    id: 'tp-mazembe',
    providerId: '1041',
    providerName: 'allsportsapi',
    name: 'TP Mazembe',
    shortName: 'TP Mazembe',
    slug: 'tp-mazembe',
    competitionId: 'COD-LINAFOOT',
    countryCode: 'CD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1041),
    stadium: 'Stade TP Mazembe',
    founded: 1939,
    globalRank: 42,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 29,
  },
  'enyimba-fc': {
    id: 'enyimba-fc',
    providerId: '1043',
    providerName: 'allsportsapi',
    name: 'Enyimba International FC',
    shortName: 'Enyimba',
    slug: 'enyimba-fc',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1043),
    stadium: 'Enyimba International Stadium',
    founded: 1976,
    globalRank: 45,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 30,
  },
  'remo-stars': {
    id: 'remo-stars',
    providerId: '1044',
    providerName: 'allsportsapi',
    name: 'Remo Stars FC',
    shortName: 'Remo Stars',
    slug: 'remo-stars',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1044),
    stadium: 'Remo Stars Stadium, Ikenne',
    founded: 2010,
    globalRank: 50,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 31,
  },
  'rangers-international': {
    id: 'rangers-international',
    providerId: '1045',
    providerName: 'allsportsapi',
    name: 'Rangers International FC',
    shortName: 'Rangers',
    slug: 'rangers-international',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1045),
    stadium: 'Nnamdi Azikiwe Stadium',
    founded: 1970,
    globalRank: 52,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 12,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 32,
  },
  'rivers-united': {
    id: 'rivers-united',
    providerId: '1046',
    providerName: 'allsportsapi',
    name: 'Rivers United FC',
    shortName: 'Rivers United',
    slug: 'rivers-united',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1046),
    stadium: 'Adokiye Amiesimaka Stadium',
    founded: 2016,
    globalRank: 55,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 13,
    isFeatured: false,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 33,
  },
  'asante-kotoko': {
    id: 'asante-kotoko',
    providerId: '1050',
    providerName: 'allsportsapi',
    name: 'Asante Kotoko SC',
    shortName: 'Kotoko',
    slug: 'asante-kotoko',
    competitionId: 'GHA-PREMIER-LEAGUE',
    countryCode: 'GH',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1050),
    stadium: 'Baba Yara Stadium',
    founded: 1935,
    globalRank: 58,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 14,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 34,
  },
  'hearts-of-oak': {
    id: 'hearts-of-oak',
    providerId: '1051',
    providerName: 'allsportsapi',
    name: 'Hearts of Oak SC',
    shortName: 'Hearts of Oak',
    slug: 'hearts-of-oak',
    competitionId: 'GHA-PREMIER-LEAGUE',
    countryCode: 'GH',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1051),
    stadium: 'Accra Sports Stadium',
    founded: 1911,
    globalRank: 60,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 15,
    isFeatured: false,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 35,
  },
  'simba-sc': {
    id: 'simba-sc',
    providerId: '1052',
    providerName: 'allsportsapi',
    name: 'Simba SC',
    shortName: 'Simba',
    slug: 'simba-sc',
    competitionId: 'TZA-PREMIER-LEAGUE',
    countryCode: 'TZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1052),
    stadium: 'Benjamin Mkapa Stadium',
    founded: 1936,
    globalRank: 48,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 16,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 36,
  },
  'young-africans': {
    id: 'young-africans',
    providerId: '1053',
    providerName: 'allsportsapi',
    name: 'Young Africans SC (Yanga)',
    shortName: 'Yanga',
    slug: 'young-africans',
    competitionId: 'TZA-PREMIER-LEAGUE',
    countryCode: 'TZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1053),
    stadium: 'Benjamin Mkapa Stadium',
    founded: 1935,
    globalRank: 49,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 17,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 37,
  },

  // ─── Saudi Pro League & Americas ───────────────────────────────────────────
  'al-hilal': {
    id: 'al-hilal',
    providerId: '2939',
    providerName: 'allsportsapi',
    name: 'Al-Hilal SFC',
    shortName: 'Al Hilal',
    slug: 'al-hilal',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2939),
    stadium: 'Kingdom Arena',
    founded: 1957,
    globalRank: 22,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 38,
  },
  'al-nassr': {
    id: 'al-nassr',
    providerId: '2938',
    providerName: 'allsportsapi',
    name: 'Al-Nassr FC',
    shortName: 'Al Nassr',
    slug: 'al-nassr',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2938),
    stadium: 'Al-Awwal Park',
    founded: 1955,
    globalRank: 24,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 39,
  },
  'inter-miami': {
    id: 'inter-miami',
    providerId: '9568',
    providerName: 'allsportsapi',
    name: 'Inter Miami CF',
    shortName: 'Inter Miami',
    slug: 'inter-miami',
    competitionId: 'USA-MLS',
    countryCode: 'US',
    confederationCode: 'CONCACAF',
    logoUrl: teamLogo(9568),
    stadium: 'Chase Stadium',
    founded: 2018,
    globalRank: 28,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 40,
  },
  'brighton': {
    id: 'brighton',
    providerId: '51',
    providerName: 'allsportsapi',
    name: "Brighton & Hove Albion",
    shortName: "Brighton",
    slug: 'brighton',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(51),
    stadium: "Amex Stadium",
    founded: 1901,
    globalRank: 35,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 30,
  },
  'west-ham': {
    id: 'west-ham',
    providerId: '48',
    providerName: 'allsportsapi',
    name: "West Ham United",
    shortName: "West Ham",
    slug: 'west-ham',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(48),
    stadium: "London Stadium",
    founded: 1895,
    globalRank: 36,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 31,
  },
  'wolverhampton-wanderers': {
    id: 'wolverhampton-wanderers',
    providerId: '39',
    providerName: 'allsportsapi',
    name: "Wolverhampton Wanderers",
    shortName: "Wolves",
    slug: 'wolverhampton-wanderers',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(39),
    stadium: "Molineux Stadium",
    founded: 1877,
    globalRank: 45,
    countryRank: 9,
    competitionRank: 9,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 32,
  },
  'crystal-palace': {
    id: 'crystal-palace',
    providerId: '52',
    providerName: 'allsportsapi',
    name: "Crystal Palace",
    shortName: "Crystal Palace",
    slug: 'crystal-palace',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(52),
    stadium: "Selhurst Park",
    founded: 1905,
    globalRank: 48,
    countryRank: 10,
    competitionRank: 10,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 33,
  },
  'everton': {
    id: 'everton',
    providerId: '45',
    providerName: 'allsportsapi',
    name: "Everton",
    shortName: "Everton",
    slug: 'everton',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(45),
    stadium: "Goodison Park",
    founded: 1878,
    globalRank: 49,
    countryRank: 11,
    competitionRank: 11,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 34,
  },
  'brentford': {
    id: 'brentford',
    providerId: '55',
    providerName: 'allsportsapi',
    name: "Brentford",
    shortName: "Brentford",
    slug: 'brentford',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(55),
    stadium: "Gtech Community Stadium",
    founded: 1889,
    globalRank: 50,
    countryRank: 12,
    competitionRank: 12,
    continentalPriority: 12,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 35,
  },
  'fulham': {
    id: 'fulham',
    providerId: '36',
    providerName: 'allsportsapi',
    name: "Fulham",
    shortName: "Fulham",
    slug: 'fulham',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(36),
    stadium: "Craven Cottage",
    founded: 1879,
    globalRank: 52,
    countryRank: 13,
    competitionRank: 13,
    continentalPriority: 13,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 36,
  },
  'bournemouth': {
    id: 'bournemouth',
    providerId: '35',
    providerName: 'allsportsapi',
    name: "AFC Bournemouth",
    shortName: "Bournemouth",
    slug: 'bournemouth',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(35),
    stadium: "Vitality Stadium",
    founded: 1899,
    globalRank: 55,
    countryRank: 14,
    competitionRank: 14,
    continentalPriority: 14,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 37,
  },
  'nottingham-forest': {
    id: 'nottingham-forest',
    providerId: '65',
    providerName: 'allsportsapi',
    name: "Nottingham Forest",
    shortName: "Nottm Forest",
    slug: 'nottingham-forest',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(65),
    stadium: "City Ground",
    founded: 1865,
    globalRank: 56,
    countryRank: 15,
    competitionRank: 15,
    continentalPriority: 15,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 38,
  },
  'leicester-city': {
    id: 'leicester-city',
    providerId: '46',
    providerName: 'allsportsapi',
    name: "Leicester City",
    shortName: "Leicester",
    slug: 'leicester-city',
    competitionId: 'ENG-PREMIER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(46),
    stadium: "King Power Stadium",
    founded: 1884,
    globalRank: 58,
    countryRank: 16,
    competitionRank: 16,
    continentalPriority: 16,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 39,
  },
  'athletic-bilbao': {
    id: 'athletic-bilbao',
    providerId: '531',
    providerName: 'allsportsapi',
    name: "Athletic Club",
    shortName: "Athletic",
    slug: 'athletic-bilbao',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(531),
    stadium: "San Mamés",
    founded: 1898,
    globalRank: 24,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 40,
  },
  'real-sociedad': {
    id: 'real-sociedad',
    providerId: '548',
    providerName: 'allsportsapi',
    name: "Real Sociedad",
    shortName: "R. Sociedad",
    slug: 'real-sociedad',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(548),
    stadium: "Reale Arena",
    founded: 1909,
    globalRank: 26,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 41,
  },
  'villarreal': {
    id: 'villarreal',
    providerId: '533',
    providerName: 'allsportsapi',
    name: "Villarreal CF",
    shortName: "Villarreal",
    slug: 'villarreal',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(533),
    stadium: "Estadio de la Cerámica",
    founded: 1923,
    globalRank: 27,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 42,
  },
  'real-betis': {
    id: 'real-betis',
    providerId: '543',
    providerName: 'allsportsapi',
    name: "Real Betis",
    shortName: "Betis",
    slug: 'real-betis',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(543),
    stadium: "Benito Villamarín",
    founded: 1907,
    globalRank: 32,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 43,
  },
  'sevilla': {
    id: 'sevilla',
    providerId: '536',
    providerName: 'allsportsapi',
    name: "Sevilla FC",
    shortName: "Sevilla",
    slug: 'sevilla',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(536),
    stadium: "Ramón Sánchez-Pizjuán",
    founded: 1890,
    globalRank: 38,
    countryRank: 9,
    competitionRank: 9,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 44,
  },
  'valencia': {
    id: 'valencia',
    providerId: '532',
    providerName: 'allsportsapi',
    name: "Valencia CF",
    shortName: "Valencia",
    slug: 'valencia',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(532),
    stadium: "Mestalla",
    founded: 1919,
    globalRank: 41,
    countryRank: 10,
    competitionRank: 10,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 45,
  },
  'girona': {
    id: 'girona',
    providerId: '547',
    providerName: 'allsportsapi',
    name: "Girona FC",
    shortName: "Girona",
    slug: 'girona',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(547),
    stadium: "Montilivi",
    founded: 1930,
    globalRank: 44,
    countryRank: 11,
    competitionRank: 11,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 46,
  },
  'celta-vigo': {
    id: 'celta-vigo',
    providerId: '538',
    providerName: 'allsportsapi',
    name: "RC Celta",
    shortName: "Celta Vigo",
    slug: 'celta-vigo',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(538),
    stadium: "Balaídos",
    founded: 1923,
    globalRank: 60,
    countryRank: 12,
    competitionRank: 12,
    continentalPriority: 12,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 47,
  },
  'mallorca': {
    id: 'mallorca',
    providerId: '798',
    providerName: 'allsportsapi',
    name: "RCD Mallorca",
    shortName: "Mallorca",
    slug: 'mallorca',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(798),
    stadium: "Son Moix",
    founded: 1916,
    globalRank: 62,
    countryRank: 13,
    competitionRank: 13,
    continentalPriority: 13,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 48,
  },
  'osasuna': {
    id: 'osasuna',
    providerId: '727',
    providerName: 'allsportsapi',
    name: "CA Osasuna",
    shortName: "Osasuna",
    slug: 'osasuna',
    competitionId: 'ESP-LA-LIGA',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(727),
    stadium: "El Sadar",
    founded: 1920,
    globalRank: 64,
    countryRank: 14,
    competitionRank: 14,
    continentalPriority: 14,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 49,
  },
  'roma': {
    id: 'roma',
    providerId: '497',
    providerName: 'allsportsapi',
    name: "AS Roma",
    shortName: "Roma",
    slug: 'roma',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(497),
    stadium: "Stadio Olimpico",
    founded: 1927,
    globalRank: 19,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 50,
  },
  'lazio': {
    id: 'lazio',
    providerId: '487',
    providerName: 'allsportsapi',
    name: "SS Lazio",
    shortName: "Lazio",
    slug: 'lazio',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(487),
    stadium: "Stadio Olimpico",
    founded: 1900,
    globalRank: 23,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 51,
  },
  'atalanta': {
    id: 'atalanta',
    providerId: '499',
    providerName: 'allsportsapi',
    name: "Atalanta BC",
    shortName: "Atalanta",
    slug: 'atalanta',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(499),
    stadium: "Gewiss Stadium",
    founded: 1907,
    globalRank: 21,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 52,
  },
  'fiorentina': {
    id: 'fiorentina',
    providerId: '502',
    providerName: 'allsportsapi',
    name: "ACF Fiorentina",
    shortName: "Fiorentina",
    slug: 'fiorentina',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(502),
    stadium: "Stadio Artemio Franchi",
    founded: 1926,
    globalRank: 33,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 53,
  },
  'bologna': {
    id: 'bologna',
    providerId: '500',
    providerName: 'allsportsapi',
    name: "Bologna FC",
    shortName: "Bologna",
    slug: 'bologna',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(500),
    stadium: "Stadio Renato Dall'Ara",
    founded: 1909,
    globalRank: 43,
    countryRank: 9,
    competitionRank: 9,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 54,
  },
  'torino': {
    id: 'torino',
    providerId: '503',
    providerName: 'allsportsapi',
    name: "Torino FC",
    shortName: "Torino",
    slug: 'torino',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(503),
    stadium: "Stadio Olimpico Grande Torino",
    founded: 1906,
    globalRank: 53,
    countryRank: 10,
    competitionRank: 10,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 55,
  },
  'genoa': {
    id: 'genoa',
    providerId: '495',
    providerName: 'allsportsapi',
    name: "Genoa CFC",
    shortName: "Genoa",
    slug: 'genoa',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(495),
    stadium: "Luigi Ferraris",
    founded: 1893,
    globalRank: 66,
    countryRank: 11,
    competitionRank: 11,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 56,
  },
  'monza': {
    id: 'monza',
    providerId: '1579',
    providerName: 'allsportsapi',
    name: "AC Monza",
    shortName: "Monza",
    slug: 'monza',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(1579),
    stadium: "U-Power Stadium",
    founded: 1912,
    globalRank: 68,
    countryRank: 12,
    competitionRank: 12,
    continentalPriority: 12,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 57,
  },
  'udinese': {
    id: 'udinese',
    providerId: '494',
    providerName: 'allsportsapi',
    name: "Udinese Calcio",
    shortName: "Udinese",
    slug: 'udinese',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(494),
    stadium: "Bluenergy Stadium",
    founded: 1896,
    globalRank: 70,
    countryRank: 13,
    competitionRank: 13,
    continentalPriority: 13,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 58,
  },
  'parma': {
    id: 'parma',
    providerId: '523',
    providerName: 'allsportsapi',
    name: "Parma Calcio",
    shortName: "Parma",
    slug: 'parma',
    competitionId: 'ITA-SERIE-A',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(523),
    stadium: "Ennio Tardini",
    founded: 1913,
    globalRank: 72,
    countryRank: 14,
    competitionRank: 14,
    continentalPriority: 14,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 59,
  },
  'rb-leipzig': {
    id: 'rb-leipzig',
    providerId: '173',
    providerName: 'allsportsapi',
    name: "RB Leipzig",
    shortName: "RB Leipzig",
    slug: 'rb-leipzig',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(173),
    stadium: "Red Bull Arena",
    founded: 2009,
    globalRank: 16,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 60,
  },
  'eintracht-frankfurt': {
    id: 'eintracht-frankfurt',
    providerId: '169',
    providerName: 'allsportsapi',
    name: "Eintracht Frankfurt",
    shortName: "Frankfurt",
    slug: 'eintracht-frankfurt',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(169),
    stadium: "Deutsche Bank Park",
    founded: 1899,
    globalRank: 25,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 61,
  },
  'stuttgart': {
    id: 'stuttgart',
    providerId: '172',
    providerName: 'allsportsapi',
    name: "VfB Stuttgart",
    shortName: "Stuttgart",
    slug: 'stuttgart',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(172),
    stadium: "MHPArena",
    founded: 1893,
    globalRank: 30,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 62,
  },
  'wolfsburg': {
    id: 'wolfsburg',
    providerId: '161',
    providerName: 'allsportsapi',
    name: "VfL Wolfsburg",
    shortName: "Wolfsburg",
    slug: 'wolfsburg',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(161),
    stadium: "Volkswagen Arena",
    founded: 1945,
    globalRank: 47,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 63,
  },
  'borussia-monchengladbach': {
    id: 'borussia-monchengladbach',
    providerId: '163',
    providerName: 'allsportsapi',
    name: "Borussia Mönchengladbach",
    shortName: "M'gladbach",
    slug: 'borussia-monchengladbach',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(163),
    stadium: "Borussia-Park",
    founded: 1900,
    globalRank: 51,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 64,
  },
  'freiburg': {
    id: 'freiburg',
    providerId: '160',
    providerName: 'allsportsapi',
    name: "SC Freiburg",
    shortName: "Freiburg",
    slug: 'freiburg',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(160),
    stadium: "Europa-Park Stadion",
    founded: 1904,
    globalRank: 54,
    countryRank: 9,
    competitionRank: 9,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 65,
  },
  'werder-bremen': {
    id: 'werder-bremen',
    providerId: '162',
    providerName: 'allsportsapi',
    name: "SV Werder Bremen",
    shortName: "Werder Bremen",
    slug: 'werder-bremen',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(162),
    stadium: "Weserstadion",
    founded: 1899,
    globalRank: 61,
    countryRank: 10,
    competitionRank: 10,
    continentalPriority: 10,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 66,
  },
  'union-berlin': {
    id: 'union-berlin',
    providerId: '182',
    providerName: 'allsportsapi',
    name: "1. FC Union Berlin",
    shortName: "Union Berlin",
    slug: 'union-berlin',
    competitionId: 'GER-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(182),
    stadium: "Stadion An der Alten Försterei",
    founded: 1966,
    globalRank: 65,
    countryRank: 11,
    competitionRank: 11,
    continentalPriority: 11,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 67,
  },
  'monaco': {
    id: 'monaco',
    providerId: '91',
    providerName: 'allsportsapi',
    name: "AS Monaco",
    shortName: "Monaco",
    slug: 'monaco',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(91),
    stadium: "Stade Louis-II",
    founded: 1924,
    globalRank: 22,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 68,
  },
  'toulouse': {
    id: 'toulouse',
    providerId: '83',
    providerName: 'allsportsapi',
    name: "Toulouse FC",
    shortName: "Toulouse",
    slug: 'toulouse',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(83),
    stadium: "Stadium de Toulouse",
    founded: 1970,
    globalRank: 73,
    countryRank: 10,
    competitionRank: 10,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 82,
  },
  'lyon': {
    id: 'lyon',
    providerId: '80',
    providerName: 'allsportsapi',
    name: "Olympique Lyonnais",
    shortName: "Lyon",
    slug: 'lyon',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(80),
    stadium: "Groupama Stadium",
    founded: 1950,
    globalRank: 31,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 70,
  },
  'lille': {
    id: 'lille',
    providerId: '79',
    providerName: 'allsportsapi',
    name: "LOSC Lille",
    shortName: "Lille",
    slug: 'lille',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(79),
    stadium: "Decathlon Arena",
    founded: 1944,
    globalRank: 34,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 71,
  },
  'rennes': {
    id: 'rennes',
    providerId: '94',
    providerName: 'allsportsapi',
    name: "Stade Rennais FC",
    shortName: "Rennes",
    slug: 'rennes',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(94),
    stadium: "Roazhon Park",
    founded: 1901,
    globalRank: 46,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 72,
  },
  'nice': {
    id: 'nice',
    providerId: '84',
    providerName: 'allsportsapi',
    name: "OGC Nice",
    shortName: "Nice",
    slug: 'nice',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(84),
    stadium: "Allianz Riviera",
    founded: 1904,
    globalRank: 57,
    countryRank: 7,
    competitionRank: 7,
    continentalPriority: 7,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 73,
  },
  'lens': {
    id: 'lens',
    providerId: '116',
    providerName: 'allsportsapi',
    name: "RC Lens",
    shortName: "Lens",
    slug: 'lens',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(116),
    stadium: "Stade Bollaert-Delelis",
    founded: 1906,
    globalRank: 59,
    countryRank: 8,
    competitionRank: 8,
    continentalPriority: 8,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 74,
  },
  'strasbourg': {
    id: 'strasbourg',
    providerId: '95',
    providerName: 'allsportsapi',
    name: "RC Strasbourg Alsace",
    shortName: "Strasbourg",
    slug: 'strasbourg',
    competitionId: 'FRA-LIGUE-1',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(95),
    stadium: "Stade de la Meinau",
    founded: 1906,
    globalRank: 71,
    countryRank: 9,
    competitionRank: 9,
    continentalPriority: 9,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 75,
  },
  'pyramids-fc': {
    id: 'pyramids-fc',
    providerId: '1041',
    providerName: 'allsportsapi',
    name: "Pyramids FC",
    shortName: "Pyramids",
    slug: 'pyramids-fc',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1041),
    stadium: "30 June Stadium",
    founded: 2008,
    globalRank: 75,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 76,
  },
  'al-masry': {
    id: 'al-masry',
    providerId: '1042',
    providerName: 'allsportsapi',
    name: "Al Masry SC",
    shortName: "Al Masry",
    slug: 'al-masry',
    competitionId: 'EGY-PREMIER-LEAGUE',
    countryCode: 'EG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1042),
    stadium: "Port Said Stadium",
    founded: 1920,
    globalRank: 90,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 77,
  },
  'as-far-rabat': {
    id: 'as-far-rabat',
    providerId: '1028',
    providerName: 'allsportsapi',
    name: "AS FAR Rabat",
    shortName: "AS FAR",
    slug: 'as-far-rabat',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1028),
    stadium: "Prince Moulay Abdellah",
    founded: 1958,
    globalRank: 78,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 78,
  },
  'rs-berkane': {
    id: 'rs-berkane',
    providerId: '1029',
    providerName: 'allsportsapi',
    name: "RS Berkane",
    shortName: "RS Berkane",
    slug: 'rs-berkane',
    competitionId: 'MAR-BOTOLA-PRO',
    countryCode: 'MA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1029),
    stadium: "Stade Municipal de Berkane",
    founded: 1938,
    globalRank: 80,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 79,
  },
  'cr-belouizdad': {
    id: 'cr-belouizdad',
    providerId: '1055',
    providerName: 'allsportsapi',
    name: "CR Belouizdad",
    shortName: "CR Belouizdad",
    slug: 'cr-belouizdad',
    competitionId: 'DZA-LIGUE-1',
    countryCode: 'DZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1055),
    stadium: "Stade 20 Août 1955",
    founded: 1962,
    globalRank: 82,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 80,
  },
  'usm-alger': {
    id: 'usm-alger',
    providerId: '1056',
    providerName: 'allsportsapi',
    name: "USM Alger",
    shortName: "USM Alger",
    slug: 'usm-alger',
    competitionId: 'DZA-LIGUE-1',
    countryCode: 'DZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1056),
    stadium: "Stade Omar Hamadi",
    founded: 1937,
    globalRank: 84,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 81,
  },
  'js-kabylie': {
    id: 'js-kabylie',
    providerId: '1057',
    providerName: 'allsportsapi',
    name: "JS Kabylie",
    shortName: "JS Kabylie",
    slug: 'js-kabylie',
    competitionId: 'DZA-LIGUE-1',
    countryCode: 'DZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1057),
    stadium: "Stade Hocine Aït Ahmed",
    founded: 1946,
    globalRank: 86,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 82,
  },
  'es-setif': {
    id: 'es-setif',
    providerId: '1058',
    providerName: 'allsportsapi',
    name: "ES Sétif",
    shortName: "ES Sétif",
    slug: 'es-setif',
    competitionId: 'DZA-LIGUE-1',
    countryCode: 'DZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1058),
    stadium: "Stade 8 Mai 1945",
    founded: 1958,
    globalRank: 88,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 83,
  },
  'etoile-du-sahel': {
    id: 'etoile-du-sahel',
    providerId: '1062',
    providerName: 'allsportsapi',
    name: "Étoile du Sahel",
    shortName: "Étoile Sahel",
    slug: 'etoile-du-sahel',
    competitionId: 'TUN-LIGUE-1',
    countryCode: 'TN',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1062),
    stadium: "Stade Olympique de Sousse",
    founded: 1925,
    globalRank: 83,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 84,
  },
  'club-africain': {
    id: 'club-africain',
    providerId: '1063',
    providerName: 'allsportsapi',
    name: "Club Africain",
    shortName: "Club Africain",
    slug: 'club-africain',
    competitionId: 'TUN-LIGUE-1',
    countryCode: 'TN',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1063),
    stadium: "Stade Hammadi Agrebi",
    founded: 1920,
    globalRank: 87,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 85,
  },
  'cs-sfaxien': {
    id: 'cs-sfaxien',
    providerId: '1064',
    providerName: 'allsportsapi',
    name: "CS Sfaxien",
    shortName: "CS Sfaxien",
    slug: 'cs-sfaxien',
    competitionId: 'TUN-LIGUE-1',
    countryCode: 'TN',
    confederationCode: 'CAF',
    logoUrl: teamLogo(1064),
    stadium: "Stade Taïeb Mhiri",
    founded: 1928,
    globalRank: 92,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 86,
  },
  'azam-fc': {
    id: 'azam-fc',
    providerId: '2090',
    providerName: 'allsportsapi',
    name: "Azam FC",
    shortName: "Azam",
    slug: 'azam-fc',
    competitionId: 'TZA-LIGI-KUU',
    countryCode: 'TZ',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2090),
    stadium: "Chamazi Stadium",
    founded: 2004,
    globalRank: 105,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 87,
  },
  'as-vita-club': {
    id: 'as-vita-club',
    providerId: '2102',
    providerName: 'allsportsapi',
    name: "AS Vita Club",
    shortName: "Vita Club",
    slug: 'as-vita-club',
    competitionId: 'COD-LINAFOOT',
    countryCode: 'CD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2102),
    stadium: "Stade des Martyrs",
    founded: 1935,
    globalRank: 91,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 88,
  },
  'saint-eloi-lupopo': {
    id: 'saint-eloi-lupopo',
    providerId: '2103',
    providerName: 'allsportsapi',
    name: "FC Saint-Éloi Lupopo",
    shortName: "Lupopo",
    slug: 'saint-eloi-lupopo',
    competitionId: 'COD-LINAFOOT',
    countryCode: 'CD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2103),
    stadium: "Stade Frédéric Kibassa Maliba",
    founded: 1939,
    globalRank: 110,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 89,
  },
  'asec-mimosas': {
    id: 'asec-mimosas',
    providerId: '2120',
    providerName: 'allsportsapi',
    name: "ASEC Mimosas",
    shortName: "ASEC",
    slug: 'asec-mimosas',
    competitionId: 'CIV-LIGUE-1',
    countryCode: 'CI',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2120),
    stadium: "Stade Félix Houphouët-Boigny",
    founded: 1948,
    globalRank: 94,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 90,
  },
  'africa-sports': {
    id: 'africa-sports',
    providerId: '2121',
    providerName: 'allsportsapi',
    name: "Africa Sports d'Abidjan",
    shortName: "Africa Sports",
    slug: 'africa-sports',
    competitionId: 'CIV-LIGUE-1',
    countryCode: 'CI',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2121),
    stadium: "Stade Robert Champroux",
    founded: 1947,
    globalRank: 112,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 91,
  },
  'zesco-united': {
    id: 'zesco-united',
    providerId: '2130',
    providerName: 'allsportsapi',
    name: "ZESCO United FC",
    shortName: "ZESCO",
    slug: 'zesco-united',
    competitionId: 'ZMB-SUPER-LEAGUE',
    countryCode: 'ZM',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2130),
    stadium: "Levy Mwanawasa Stadium",
    founded: 1974,
    globalRank: 98,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 92,
  },
  'nkana-fc': {
    id: 'nkana-fc',
    providerId: '2131',
    providerName: 'allsportsapi',
    name: "Nkana FC",
    shortName: "Nkana",
    slug: 'nkana-fc',
    competitionId: 'ZMB-SUPER-LEAGUE',
    countryCode: 'ZM',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2131),
    stadium: "Nkana Stadium",
    founded: 1935,
    globalRank: 114,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 93,
  },
  'gor-mahia': {
    id: 'gor-mahia',
    providerId: '2140',
    providerName: 'allsportsapi',
    name: "Gor Mahia FC",
    shortName: "Gor Mahia",
    slug: 'gor-mahia',
    competitionId: 'KEN-PREMIER-LEAGUE',
    countryCode: 'KE',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2140),
    stadium: "Nyayo National Stadium",
    founded: 1968,
    globalRank: 99,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 94,
  },
  'afc-leopards': {
    id: 'afc-leopards',
    providerId: '2141',
    providerName: 'allsportsapi',
    name: "AFC Leopards",
    shortName: "AFC Leopards",
    slug: 'afc-leopards',
    competitionId: 'KEN-PREMIER-LEAGUE',
    countryCode: 'KE',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2141),
    stadium: "Nyayo National Stadium",
    founded: 1964,
    globalRank: 115,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 95,
  },
  'petro-de-luanda': {
    id: 'petro-de-luanda',
    providerId: '2150',
    providerName: 'allsportsapi',
    name: "Atlético Petróleos de Luanda",
    shortName: "Petro Luanda",
    slug: 'petro-de-luanda',
    competitionId: 'AGO-GIRABOLA',
    countryCode: 'AO',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2150),
    stadium: "Estádio 11 de Novembro",
    founded: 1980,
    globalRank: 81,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 96,
  },
  'primeiro-de-agosto': {
    id: 'primeiro-de-agosto',
    providerId: '2151',
    providerName: 'allsportsapi',
    name: "CD Primeiro de Agosto",
    shortName: "1º de Agosto",
    slug: 'primeiro-de-agosto',
    competitionId: 'AGO-GIRABOLA',
    countryCode: 'AO',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2151),
    stadium: "Estádio 11 de Novembro",
    founded: 1977,
    globalRank: 102,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 97,
  },
  'vipers-sc': {
    id: 'vipers-sc',
    providerId: '2160',
    providerName: 'allsportsapi',
    name: "Vipers SC",
    shortName: "Vipers",
    slug: 'vipers-sc',
    competitionId: 'UGA-PREMIER-LEAGUE',
    countryCode: 'UG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2160),
    stadium: "St. Mary's Stadium-Kitende",
    founded: 1969,
    globalRank: 104,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 98,
  },
  'kcca-fc': {
    id: 'kcca-fc',
    providerId: '2161',
    providerName: 'allsportsapi',
    name: "Kampala Capital City Authority FC",
    shortName: "KCCA",
    slug: 'kcca-fc',
    competitionId: 'UGA-PREMIER-LEAGUE',
    countryCode: 'UG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2161),
    stadium: "MTN Omondi Stadium",
    founded: 1963,
    globalRank: 116,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 99,
  },
  'al-hilal-omdurman': {
    id: 'al-hilal-omdurman',
    providerId: '2170',
    providerName: 'allsportsapi',
    name: "Al Hilal SC",
    shortName: "Al Hilal",
    slug: 'al-hilal-omdurman',
    competitionId: 'SDN-PREMIER-LEAGUE',
    countryCode: 'SD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2170),
    stadium: "Al-Hilal Stadium",
    founded: 1930,
    globalRank: 88,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 100,
  },
  'al-merrikh': {
    id: 'al-merrikh',
    providerId: '2171',
    providerName: 'allsportsapi',
    name: "Al Merrikh SC",
    shortName: "Al Merrikh",
    slug: 'al-merrikh',
    competitionId: 'SDN-PREMIER-LEAGUE',
    countryCode: 'SD',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2171),
    stadium: "Al-Merrikh Stadium",
    founded: 1908,
    globalRank: 97,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 101,
  },
  'coton-sport': {
    id: 'coton-sport',
    providerId: '2180',
    providerName: 'allsportsapi',
    name: "Coton Sport FC de Garoua",
    shortName: "Coton Sport",
    slug: 'coton-sport',
    competitionId: 'CMR-ELITE-ONE',
    countryCode: 'CM',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2180),
    stadium: "Stade Roumdé Adjia",
    founded: 1986,
    globalRank: 96,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 102,
  },
  'canon-yaounde': {
    id: 'canon-yaounde',
    providerId: '2181',
    providerName: 'allsportsapi',
    name: "Canon Sportif de Yaoundé",
    shortName: "Canon Yaoundé",
    slug: 'canon-yaounde',
    competitionId: 'CMR-ELITE-ONE',
    countryCode: 'CM',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2181),
    stadium: "Stade Ahmadou Ahidjo",
    founded: 1930,
    globalRank: 118,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 103,
  },
  'kano-pillars': {
    id: 'kano-pillars',
    providerId: '2190',
    providerName: 'allsportsapi',
    name: "Kano Pillars FC",
    shortName: "Kano Pillars",
    slug: 'kano-pillars',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2190),
    stadium: "Sani Abacha Stadium",
    founded: 1990,
    globalRank: 100,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 104,
  },
  'shooting-stars': {
    id: 'shooting-stars',
    providerId: '2193',
    providerName: 'allsportsapi',
    name: "Shooting Stars SC",
    shortName: "3SC",
    slug: 'shooting-stars',
    competitionId: 'NGA-NPFL',
    countryCode: 'NG',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2193),
    stadium: "Lekan Salami Stadium",
    founded: 1950,
    globalRank: 108,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 105,
  },
  'supersport-united': {
    id: 'supersport-united',
    providerId: '2201',
    providerName: 'allsportsapi',
    name: "SuperSport United FC",
    shortName: "SuperSport",
    slug: 'supersport-united',
    competitionId: 'ZAF-PREMIER-SOCCER-LEAGUE',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2201),
    stadium: "Lucas Moripe Stadium",
    founded: 1994,
    globalRank: 107,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 106,
  },
  'cape-town-city': {
    id: 'cape-town-city',
    providerId: '2202',
    providerName: 'allsportsapi',
    name: "Cape Town City FC",
    shortName: "CT City",
    slug: 'cape-town-city',
    competitionId: 'ZAF-PREMIER-SOCCER-LEAGUE',
    countryCode: 'ZA',
    confederationCode: 'CAF',
    logoUrl: teamLogo(2202),
    stadium: "DHL Stadium",
    founded: 2016,
    globalRank: 109,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: true,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 107,
  },
  'river-plate': {
    id: 'river-plate',
    providerId: '435',
    providerName: 'allsportsapi',
    name: "CA River Plate",
    shortName: "River Plate",
    slug: 'river-plate',
    competitionId: 'ARG-LIGA-PROFESIONAL',
    countryCode: 'AR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(435),
    stadium: "El Monumental",
    founded: 1901,
    globalRank: 14,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 108,
  },
  'boca-juniors': {
    id: 'boca-juniors',
    providerId: '451',
    providerName: 'allsportsapi',
    name: "CA Boca Juniors",
    shortName: "Boca Juniors",
    slug: 'boca-juniors',
    competitionId: 'ARG-LIGA-PROFESIONAL',
    countryCode: 'AR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(451),
    stadium: "La Bombonera",
    founded: 1905,
    globalRank: 15,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 109,
  },
  'flamengo': {
    id: 'flamengo',
    providerId: '127',
    providerName: 'allsportsapi',
    name: "CR Flamengo",
    shortName: "Flamengo",
    slug: 'flamengo',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(127),
    stadium: "Maracanã",
    founded: 1895,
    globalRank: 17,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 110,
  },
  'palmeiras': {
    id: 'palmeiras',
    providerId: '121',
    providerName: 'allsportsapi',
    name: "SE Palmeiras",
    shortName: "Palmeiras",
    slug: 'palmeiras',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(121),
    stadium: "Allianz Parque",
    founded: 1914,
    globalRank: 18,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 111,
  },
  'sao-paulo': {
    id: 'sao-paulo',
    providerId: '126',
    providerName: 'allsportsapi',
    name: "São Paulo FC",
    shortName: "São Paulo",
    slug: 'sao-paulo',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(126),
    stadium: "Morumbi",
    founded: 1930,
    globalRank: 20,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 112,
  },
  'corinthians': {
    id: 'corinthians',
    providerId: '131',
    providerName: 'allsportsapi',
    name: "SC Corinthians Paulista",
    shortName: "Corinthians",
    slug: 'corinthians',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(131),
    stadium: "Neo Química Arena",
    founded: 1910,
    globalRank: 28,
    countryRank: 4,
    competitionRank: 4,
    continentalPriority: 4,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 113,
  },
  'fluminense': {
    id: 'fluminense',
    providerId: '124',
    providerName: 'allsportsapi',
    name: "Fluminense FC",
    shortName: "Fluminense",
    slug: 'fluminense',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(124),
    stadium: "Maracanã",
    founded: 1902,
    globalRank: 37,
    countryRank: 5,
    competitionRank: 5,
    continentalPriority: 5,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 114,
  },
  'gremio': {
    id: 'gremio',
    providerId: '130',
    providerName: 'allsportsapi',
    name: "Grêmio FBPA",
    shortName: "Grêmio",
    slug: 'gremio',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(130),
    stadium: "Arena do Grêmio",
    founded: 1903,
    globalRank: 40,
    countryRank: 6,
    competitionRank: 6,
    continentalPriority: 6,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 115,
  },
  'al-hilal-saudi': {
    id: 'al-hilal-saudi',
    providerId: '2939',
    providerName: 'allsportsapi',
    name: "Al Hilal SFC",
    shortName: "Al Hilal",
    slug: 'al-hilal-saudi',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2939),
    stadium: "Kingdom Arena",
    founded: 1957,
    globalRank: 39,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 116,
  },
  'al-ittihad': {
    id: 'al-ittihad',
    providerId: '2932',
    providerName: 'allsportsapi',
    name: "Al Ittihad Club",
    shortName: "Al Ittihad",
    slug: 'al-ittihad',
    competitionId: 'SAU-PRO-LEAGUE',
    countryCode: 'SA',
    confederationCode: 'AFC',
    logoUrl: teamLogo(2932),
    stadium: "King Abdullah Sports City",
    founded: 1927,
    globalRank: 63,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 117,
  },
  'urawa-red-diamonds': {
    id: 'urawa-red-diamonds',
    providerId: '285',
    providerName: 'allsportsapi',
    name: "Urawa Red Diamonds",
    shortName: "Urawa Reds",
    slug: 'urawa-red-diamonds',
    competitionId: 'JPN-J1-LEAGUE',
    countryCode: 'JP',
    confederationCode: 'AFC',
    logoUrl: teamLogo(285),
    stadium: "Saitama Stadium 2002",
    founded: 1950,
    globalRank: 67,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 118,
  },
  'yokohama-f-marinos': {
    id: 'yokohama-f-marinos',
    providerId: '282',
    providerName: 'allsportsapi',
    name: "Yokohama F. Marinos",
    shortName: "Yokohama FM",
    slug: 'yokohama-f-marinos',
    competitionId: 'JPN-J1-LEAGUE',
    countryCode: 'JP',
    confederationCode: 'AFC',
    logoUrl: teamLogo(282),
    stadium: "Nissan Stadium",
    founded: 1972,
    globalRank: 69,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 119,
  },
  'chelsea-women': {
    id: 'chelsea-women',
    providerId: '10043',
    providerName: 'allsportsapi',
    name: "Chelsea FC Women",
    shortName: "Chelsea Women",
    slug: 'chelsea-women',
    competitionId: 'ENG-WOMENS-SUPER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10043),
    stadium: "Kingsmeadow",
    founded: 1992,
    globalRank: 5,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 120,
  },
  'arsenal-women': {
    id: 'arsenal-women',
    providerId: '10042',
    providerName: 'allsportsapi',
    name: "Arsenal Women FC",
    shortName: "Arsenal Women",
    slug: 'arsenal-women',
    competitionId: 'ENG-WOMENS-SUPER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10042),
    stadium: "Meadow Park / Emirates",
    founded: 1987,
    globalRank: 6,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 121,
  },
  'manchester-city-women': {
    id: 'manchester-city-women',
    providerId: '10050',
    providerName: 'allsportsapi',
    name: "Manchester City Women",
    shortName: "Man City Women",
    slug: 'manchester-city-women',
    competitionId: 'ENG-WOMENS-SUPER-LEAGUE',
    countryCode: 'GB-ENG',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10050),
    stadium: "Joie Stadium",
    founded: 1988,
    globalRank: 7,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 122,
  },
  'barcelona-femeni': {
    id: 'barcelona-femeni',
    providerId: '10529',
    providerName: 'allsportsapi',
    name: "FC Barcelona Femení",
    shortName: "Barça Femení",
    slug: 'barcelona-femeni',
    competitionId: 'ESP-LIGA-F',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10529),
    stadium: "Estadi Johan Cruyff",
    founded: 1988,
    globalRank: 1,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 123,
  },
  'real-madrid-femenino': {
    id: 'real-madrid-femenino',
    providerId: '10541',
    providerName: 'allsportsapi',
    name: "Real Madrid Femenino",
    shortName: "Real Madrid Fem",
    slug: 'real-madrid-femenino',
    competitionId: 'ESP-LIGA-F',
    countryCode: 'ES',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10541),
    stadium: "Alfredo Di Stéfano",
    founded: 2014,
    globalRank: 8,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 124,
  },
  'lyon-feminin': {
    id: 'lyon-feminin',
    providerId: '10080',
    providerName: 'allsportsapi',
    name: "Olympique Lyonnais Féminin",
    shortName: "Lyon Féminin",
    slug: 'lyon-feminin',
    competitionId: 'FRA-PREMIERE-LIGUE',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10080),
    stadium: "Groupama OL Training Center",
    founded: 1970,
    globalRank: 2,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 125,
  },
  'psg-feminin': {
    id: 'psg-feminin',
    providerId: '10085',
    providerName: 'allsportsapi',
    name: "Paris Saint-Germain Féminine",
    shortName: "PSG Féminine",
    slug: 'psg-feminin',
    competitionId: 'FRA-PREMIERE-LIGUE',
    countryCode: 'FR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10085),
    stadium: "Campus PSG",
    founded: 1971,
    globalRank: 9,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 126,
  },
  'wolfsburg-frauen': {
    id: 'wolfsburg-frauen',
    providerId: '10161',
    providerName: 'allsportsapi',
    name: "VfL Wolfsburg Frauen",
    shortName: "Wolfsburg Frauen",
    slug: 'wolfsburg-frauen',
    competitionId: 'GER-FRAUEN-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10161),
    stadium: "AOK Stadion",
    founded: 2003,
    globalRank: 4,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 127,
  },
  'bayern-frauen': {
    id: 'bayern-frauen',
    providerId: '10157',
    providerName: 'allsportsapi',
    name: "FC Bayern München Frauen",
    shortName: "Bayern Frauen",
    slug: 'bayern-frauen',
    competitionId: 'GER-FRAUEN-BUNDESLIGA',
    countryCode: 'DE',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10157),
    stadium: "FC Bayern Campus",
    founded: 1970,
    globalRank: 3,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 128,
  },
  'juventus-women': {
    id: 'juventus-women',
    providerId: '10496',
    providerName: 'allsportsapi',
    name: "Juventus Women",
    shortName: "Juventus Women",
    slug: 'juventus-women',
    competitionId: 'ITA-SERIE-A-FEMMINILE',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10496),
    stadium: "Stadio Lamarmora-Pozzo",
    founded: 2017,
    globalRank: 11,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 129,
  },
  'roma-femminile': {
    id: 'roma-femminile',
    providerId: '10497',
    providerName: 'allsportsapi',
    name: "AS Roma Femminile",
    shortName: "Roma Femminile",
    slug: 'roma-femminile',
    competitionId: 'ITA-SERIE-A-FEMMINILE',
    countryCode: 'IT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(10497),
    stadium: "Stadio Tre Fontane",
    founded: 2018,
    globalRank: 12,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: true,
    priorityRank: 130,
  },
  'celtic': {
    id: 'celtic',
    providerId: '9101',
    providerName: 'allsportsapi',
    name: "Celtic FC",
    shortName: "Celtic",
    slug: 'celtic',
    competitionId: 'SCO-PREMIERSHIP',
    countryCode: 'GB-SCT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9101),
    stadium: "Celtic Park",
    founded: 1888,
    globalRank: 52,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 131,
  },
  'rangers-fc': {
    id: 'rangers-fc',
    providerId: '9102',
    providerName: 'allsportsapi',
    name: "Rangers FC",
    shortName: "Rangers",
    slug: 'rangers-fc',
    competitionId: 'SCO-PREMIERSHIP',
    countryCode: 'GB-SCT',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9102),
    stadium: "Ibrox Stadium",
    founded: 1872,
    globalRank: 54,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 132,
  },
  'galatasaray': {
    id: 'galatasaray',
    providerId: '9103',
    providerName: 'allsportsapi',
    name: "Galatasaray SK",
    shortName: "Galatasaray",
    slug: 'galatasaray',
    competitionId: 'TUR-SUPER-LIG',
    countryCode: 'TR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9103),
    stadium: "Rams Park",
    founded: 1905,
    globalRank: 48,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 133,
  },
  'fenerbahce': {
    id: 'fenerbahce',
    providerId: '9104',
    providerName: 'allsportsapi',
    name: "Fenerbahçe SK",
    shortName: "Fenerbahçe",
    slug: 'fenerbahce',
    competitionId: 'TUR-SUPER-LIG',
    countryCode: 'TR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9104),
    stadium: "Şükrü Saracoğlu",
    founded: 1907,
    globalRank: 49,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 134,
  },
  'besiktas': {
    id: 'besiktas',
    providerId: '9105',
    providerName: 'allsportsapi',
    name: "Beşiktaş JK",
    shortName: "Beşiktaş",
    slug: 'besiktas',
    competitionId: 'TUR-SUPER-LIG',
    countryCode: 'TR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9105),
    stadium: "Tüpraş Stadyumu",
    founded: 1903,
    globalRank: 58,
    countryRank: 3,
    competitionRank: 3,
    continentalPriority: 3,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 135,
  },
  'shakhtar-donetsk': {
    id: 'shakhtar-donetsk',
    providerId: '9106',
    providerName: 'allsportsapi',
    name: "FC Shakhtar Donetsk",
    shortName: "Shakhtar",
    slug: 'shakhtar-donetsk',
    competitionId: 'UKR-PREMIER-LEAGUE',
    countryCode: 'UA',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9106),
    stadium: "Donbass Arena",
    founded: 1936,
    globalRank: 50,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 136,
  },
  'dynamo-kyiv': {
    id: 'dynamo-kyiv',
    providerId: '9107',
    providerName: 'allsportsapi',
    name: "FC Dynamo Kyiv",
    shortName: "Dynamo Kyiv",
    slug: 'dynamo-kyiv',
    competitionId: 'UKR-PREMIER-LEAGUE',
    countryCode: 'UA',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9107),
    stadium: "NSC Olimpiyskiy",
    founded: 1927,
    globalRank: 60,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 137,
  },
  'red-star-belgrade': {
    id: 'red-star-belgrade',
    providerId: '9108',
    providerName: 'allsportsapi',
    name: "FK Crvena Zvezda",
    shortName: "Red Star",
    slug: 'red-star-belgrade',
    competitionId: 'SRB-SUPER-LIGA',
    countryCode: 'RS',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9108),
    stadium: "Rajko Mitić Stadium",
    founded: 1945,
    globalRank: 62,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 138,
  },
  'dinamo-zagreb': {
    id: 'dinamo-zagreb',
    providerId: '9109',
    providerName: 'allsportsapi',
    name: "GNK Dinamo Zagreb",
    shortName: "Dinamo Zagreb",
    slug: 'dinamo-zagreb',
    competitionId: 'CRO-HNL',
    countryCode: 'HR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9109),
    stadium: "Stadion Maksimir",
    founded: 1945,
    globalRank: 64,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 139,
  },
  'olympiacos': {
    id: 'olympiacos',
    providerId: '9110',
    providerName: 'allsportsapi',
    name: "Olympiacos FC",
    shortName: "Olympiacos",
    slug: 'olympiacos',
    competitionId: 'GRE-SUPER-LEAGUE',
    countryCode: 'GR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9110),
    stadium: "Karaiskakis Stadium",
    founded: 1925,
    globalRank: 59,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 140,
  },
  'slavia-prague': {
    id: 'slavia-prague',
    providerId: '9111',
    providerName: 'allsportsapi',
    name: "SK Slavia Prague",
    shortName: "Slavia Prague",
    slug: 'slavia-prague',
    competitionId: 'CZE-FIRST-LEAGUE',
    countryCode: 'CZ',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9111),
    stadium: "Fortuna Arena",
    founded: 1892,
    globalRank: 57,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 141,
  },
  'sparta-prague': {
    id: 'sparta-prague',
    providerId: '9112',
    providerName: 'allsportsapi',
    name: "AC Sparta Prague",
    shortName: "Sparta Prague",
    slug: 'sparta-prague',
    competitionId: 'CZE-FIRST-LEAGUE',
    countryCode: 'CZ',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9112),
    stadium: "epet ARENA",
    founded: 1893,
    globalRank: 61,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 142,
  },
  'young-boys': {
    id: 'young-boys',
    providerId: '9113',
    providerName: 'allsportsapi',
    name: "BSC Young Boys",
    shortName: "Young Boys",
    slug: 'young-boys',
    competitionId: 'SUI-SUPER-LEAGUE',
    countryCode: 'CH',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9113),
    stadium: "Stadion Wankdorf",
    founded: 1898,
    globalRank: 66,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 143,
  },
  'basel': {
    id: 'basel',
    providerId: '9114',
    providerName: 'allsportsapi',
    name: "FC Basel",
    shortName: "Basel",
    slug: 'basel',
    competitionId: 'SUI-SUPER-LEAGUE',
    countryCode: 'CH',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9114),
    stadium: "St. Jakob-Park",
    founded: 1893,
    globalRank: 70,
    countryRank: 2,
    competitionRank: 2,
    continentalPriority: 2,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 144,
  },
  'panathinaikos': {
    id: 'panathinaikos',
    providerId: '9201',
    providerName: 'allsportsapi',
    name: "Panathinaikos FC",
    shortName: "Panathinaikos",
    slug: 'panathinaikos',
    competitionId: 'GRE-SUPER-LEAGUE',
    countryCode: 'GR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9201),
    stadium: "Apostolos Nikolaidis",
    founded: 1908,
    globalRank: 65,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 145,
  },
  'paok-thessaloniki': {
    id: 'paok-thessaloniki',
    providerId: '9202',
    providerName: 'allsportsapi',
    name: "PAOK FC",
    shortName: "PAOK",
    slug: 'paok-thessaloniki',
    competitionId: 'GRE-SUPER-LEAGUE',
    countryCode: 'GR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9202),
    stadium: "Toumba Stadium",
    founded: 1926,
    globalRank: 68,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 146,
  },
  'aek-athens': {
    id: 'aek-athens',
    providerId: '9203',
    providerName: 'allsportsapi',
    name: "AEK Athens FC",
    shortName: "AEK Athens",
    slug: 'aek-athens',
    competitionId: 'GRE-SUPER-LEAGUE',
    countryCode: 'GR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9203),
    stadium: "OPAP Arena",
    founded: 1924,
    globalRank: 70,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 147,
  },
  'partizan-belgrade': {
    id: 'partizan-belgrade',
    providerId: '9204',
    providerName: 'allsportsapi',
    name: "FK Partizan",
    shortName: "Partizan",
    slug: 'partizan-belgrade',
    competitionId: 'SRB-SUPER-LIGA',
    countryCode: 'RS',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9204),
    stadium: "Partizan Stadium",
    founded: 1945,
    globalRank: 72,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 148,
  },
  'hajduk-split': {
    id: 'hajduk-split',
    providerId: '9205',
    providerName: 'allsportsapi',
    name: "HNK Hajduk Split",
    shortName: "Hajduk Split",
    slug: 'hajduk-split',
    competitionId: 'CRO-HNL',
    countryCode: 'HR',
    confederationCode: 'UEFA',
    logoUrl: teamLogo(9205),
    stadium: "Poljud Stadium",
    founded: 1911,
    globalRank: 74,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 149,
  },
  'clube-atletico-mineiro': {
    id: 'clube-atletico-mineiro',
    providerId: '9206',
    providerName: 'allsportsapi',
    name: "Clube Atlético Mineiro",
    shortName: "Atlético Mineiro",
    slug: 'clube-atletico-mineiro',
    competitionId: 'BRA-SERIE-A',
    countryCode: 'BR',
    confederationCode: 'CONMEBOL',
    logoUrl: teamLogo(9206),
    stadium: "Arena MRV",
    founded: 1908,
    globalRank: 35,
    countryRank: 1,
    competitionRank: 1,
    continentalPriority: 1,
    isFeatured: true,
    isPopular: true,
    isAfrican: false,
    isNationalTeam: false,
    isWomens: false,
    priorityRank: 150,
  },
};

export const PRIORITY_CLUBS_LIST: PriorityClub[] = Object.values(PRIORITY_CLUBS).sort(
  (a, b) => a.priorityRank - b.priorityRank
);

const CLUB_SLUG_MAP = new Map<string, PriorityClub>();
for (const club of PRIORITY_CLUBS_LIST) {
  CLUB_SLUG_MAP.set(club.slug.toLowerCase(), club);
  CLUB_SLUG_MAP.set(club.id.toLowerCase(), club);
}

export function getPriorityClub(idOrSlug: string): PriorityClub | undefined {
  if (!idOrSlug) return undefined;
  return CLUB_SLUG_MAP.get(idOrSlug.trim().toLowerCase());
}

export function getClubsByCompetition(compCanonicalIdOrSlug: string): PriorityClub[] {
  const norm = compCanonicalIdOrSlug.trim().toLowerCase();
  return PRIORITY_CLUBS_LIST.filter(
    (c) => c.competitionId.toLowerCase() === norm || c.competitionId.toLowerCase().includes(norm)
  );
}

export function getClubsByCountry(countryCode: string): PriorityClub[] {
  const code = countryCode.toUpperCase();
  return PRIORITY_CLUBS_LIST.filter((c) => c.countryCode === code);
}

export function getAfricanClubs(): PriorityClub[] {
  return PRIORITY_CLUBS_LIST.filter((c) => c.isAfrican);
}

export function getFeaturedClubs(): PriorityClub[] {
  return PRIORITY_CLUBS_LIST.filter((c) => c.isFeatured);
}
