import {
  CompetitionFormatConfig,
  CompetitionFormatType,
  CompetitionStage,
} from '@goalmills/types';

/**
 * Registry of Season-Specific Competition Formats.
 * Keyed by: `${competitionId}:${seasonId}` (or fallback `${competitionId}:default`).
 *
 * Demonstrates:
 * - Pure domestic leagues (LEAGUE)
 * - Knockout tournaments (KNOCKOUT)
 * - Group stage + Knockout hybrid (HYBRID with GROUP_STAGE)
 * - League Phase + Knockout hybrid (HYBRID with LEAGUE_PHASE, e.g. UCL 2024+)
 * - Historic vs Modern format evolution (season-specific!)
 */
export const COMPETITION_FORMAT_REGISTRY: Record<string, CompetitionFormatConfig> = {
  // ─── English Premier League (Pure Domestic Single Table) ───────────────────
  'ENG-PREMIER-LEAGUE:default': {
    id: 'ENG-PREMIER-LEAGUE:default',
    competitionId: 'ENG-PREMIER-LEAGUE',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'Premier League Format',
    description: 'Double round-robin single standings table of 20 clubs (38 matchdays).',
    stages: [
      {
        id: 'stage-epl-league',
        competitionId: 'ENG-PREMIER-LEAGUE',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-STANDARD-3PT',
      },
    ],
    defaultStageId: 'stage-epl-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-STANDARD-3PT',
  },

  // ─── Spanish La Liga (Pure Domestic Single Table, H2H Ruleset) ─────────────
  'ESP-LA-LIGA:default': {
    id: 'ESP-LA-LIGA:default',
    competitionId: 'ESP-LA-LIGA',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'La Liga Format',
    description: 'Double round-robin single standings table of 20 clubs with head-to-head tiebreakers.',
    stages: [
      {
        id: 'stage-laliga-league',
        competitionId: 'ESP-LA-LIGA',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-H2H-FIRST',
      },
    ],
    defaultStageId: 'stage-laliga-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-H2H-FIRST',
  },

  // ─── Italian Serie A (Pure Domestic Single Table) ──────────────────────────
  'ITA-SERIE-A:default': {
    id: 'ITA-SERIE-A:default',
    competitionId: 'ITA-SERIE-A',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'Serie A Format',
    description: 'Double round-robin single standings table of 20 clubs.',
    stages: [
      {
        id: 'stage-seriea-league',
        competitionId: 'ITA-SERIE-A',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-H2H-FIRST',
      },
    ],
    defaultStageId: 'stage-seriea-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-H2H-FIRST',
  },

  // ─── German Bundesliga (Pure Domestic Single Table of 18 Clubs) ────────────
  'GER-BUNDESLIGA:default': {
    id: 'GER-BUNDESLIGA:default',
    competitionId: 'GER-BUNDESLIGA',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'Bundesliga Format',
    description: 'Double round-robin single standings table of 18 clubs.',
    stages: [
      {
        id: 'stage-bundesliga-league',
        competitionId: 'GER-BUNDESLIGA',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-STANDARD-3PT',
      },
    ],
    defaultStageId: 'stage-bundesliga-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-STANDARD-3PT',
  },

  // ─── French Ligue 1 ────────────────────────────────────────────────────────
  'FRA-LIGUE-1:default': {
    id: 'FRA-LIGUE-1:default',
    competitionId: 'FRA-LIGUE-1',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'Ligue 1 Format',
    description: 'Double round-robin single standings table of 18 clubs.',
    stages: [
      {
        id: 'stage-ligue1-league',
        competitionId: 'FRA-LIGUE-1',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-STANDARD-3PT',
      },
    ],
    defaultStageId: 'stage-ligue1-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-STANDARD-3PT',
  },

  // ─── Nigerian NPFL ─────────────────────────────────────────────────────────
  'NGA-NPFL:default': {
    id: 'NGA-NPFL:default',
    competitionId: 'NGA-NPFL',
    seasonId: 'default',
    formatType: 'LEAGUE',
    name: 'NPFL Format',
    description: 'Nigeria Premier Football League 20-club single standings table.',
    stages: [
      {
        id: 'stage-npfl-league',
        competitionId: 'NGA-NPFL',
        seasonId: 'default',
        name: 'Regular Season',
        slug: 'regular-season',
        type: 'LEAGUE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-STANDARD-3PT',
      },
    ],
    defaultStageId: 'stage-npfl-league',
    hasGroups: false,
    hasKnockout: false,
    hasLeagueTable: true,
    rulesetId: 'RULESET-STANDARD-3PT',
  },

  // ─── FA Cup (Pure Knockout Tournament) ─────────────────────────────────────
  'ENG-FA-CUP:default': {
    id: 'ENG-FA-CUP:default',
    competitionId: 'ENG-FA-CUP',
    seasonId: 'default',
    formatType: 'KNOCKOUT',
    name: 'FA Cup Knockout Format',
    description: 'Single-elimination domestic knockout tournament without league standings.',
    stages: [
      {
        id: 'stage-facup-qualifying',
        competitionId: 'ENG-FA-CUP',
        seasonId: 'default',
        name: 'Qualifying Rounds',
        slug: 'qualifying',
        type: 'QUALIFICATION',
        order: 1,
        status: 'COMPLETED',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: true,
        rulesetId: 'RULESET-KNOCKOUT',
      },
      {
        id: 'stage-facup-main',
        competitionId: 'ENG-FA-CUP',
        seasonId: 'default',
        name: 'Main Tournament Knockout',
        slug: 'knockout',
        type: 'KNOCKOUT',
        order: 2,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-facup-main',
    hasGroups: false,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-KNOCKOUT',
  },

  // ─── FIFA World Cup 2026 (48 Teams, 12 Groups of 4 -> Round of 32) ────────
  'FIFA-WORLD-CUP:2026': {
    id: 'FIFA-WORLD-CUP:2026',
    competitionId: 'FIFA-WORLD-CUP',
    seasonId: '2026',
    formatType: 'HYBRID',
    name: 'FIFA World Cup 2026 Format',
    description: '48 teams in 12 groups of 4; top 2 and 8 best 3rd-placed advance to Round of 32.',
    stages: [
      {
        id: 'stage-wc2026-groups',
        competitionId: 'FIFA-WORLD-CUP',
        seasonId: '2026',
        name: 'Group Stage',
        slug: 'group-stage',
        type: 'GROUP_STAGE',
        order: 1,
        status: 'UPCOMING',
        isGroupStage: true,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        groupsCount: 12,
        advancingTeamsCount: 32,
        rulesetId: 'RULESET-FIFA-TOURNAMENT',
      },
      {
        id: 'stage-wc2026-knockout',
        competitionId: 'FIFA-WORLD-CUP',
        seasonId: '2026',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 2,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-wc2026-groups',
    hasGroups: true,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-FIFA-TOURNAMENT',
  },

  'FIFA-WORLD-CUP:default': {
    id: 'FIFA-WORLD-CUP:default',
    competitionId: 'FIFA-WORLD-CUP',
    seasonId: 'default',
    formatType: 'HYBRID',
    name: 'FIFA World Cup Format',
    description: 'Tournament format with Group Stage followed by single-elimination Knockout bracket.',
    stages: [
      {
        id: 'stage-wc-groups',
        competitionId: 'FIFA-WORLD-CUP',
        seasonId: 'default',
        name: 'Group Stage',
        slug: 'group-stage',
        type: 'GROUP_STAGE',
        order: 1,
        status: 'UPCOMING',
        isGroupStage: true,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        groupsCount: 12,
        advancingTeamsCount: 32,
        rulesetId: 'RULESET-FIFA-TOURNAMENT',
      },
      {
        id: 'stage-wc-knockout',
        competitionId: 'FIFA-WORLD-CUP',
        seasonId: 'default',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 2,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-wc-groups',
    hasGroups: true,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-FIFA-TOURNAMENT',
  },

  // ─── Africa Cup of Nations (CAF-AFCON: 6 Groups of 4 -> R16) ───────────────
  'CAF-AFCON:default': {
    id: 'CAF-AFCON:default',
    competitionId: 'CAF-AFCON',
    seasonId: 'default',
    formatType: 'HYBRID',
    name: 'AFCON Tournament Format',
    description: '24 nations in 6 groups of 4; top 2 plus 4 best 3rd-placed advance to Round of 16.',
    stages: [
      {
        id: 'stage-afcon-groups',
        competitionId: 'CAF-AFCON',
        seasonId: 'default',
        name: 'Group Stage',
        slug: 'group-stage',
        type: 'GROUP_STAGE',
        order: 1,
        status: 'UPCOMING',
        isGroupStage: true,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        groupsCount: 6,
        advancingTeamsCount: 16,
        rulesetId: 'RULESET-CAF-GROUP-STAGE',
      },
      {
        id: 'stage-afcon-knockout',
        competitionId: 'CAF-AFCON',
        seasonId: 'default',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 2,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-afcon-groups',
    hasGroups: true,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-CAF-GROUP-STAGE',
  },

  // ─── CAF Champions League (Preliminary -> 4 Groups of 4 -> QF Knockout) ───
  'CAF-CHAMPIONS-LEAGUE:default': {
    id: 'CAF-CHAMPIONS-LEAGUE:default',
    competitionId: 'CAF-CHAMPIONS-LEAGUE',
    seasonId: 'default',
    formatType: 'HYBRID',
    name: 'CAF Champions League Format',
    description: 'Two preliminary knockout rounds -> 16-team group stage (4 groups of 4) -> Quarter-finals knockout.',
    stages: [
      {
        id: 'stage-ccl-prelim',
        competitionId: 'CAF-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'Preliminary Rounds',
        slug: 'preliminary',
        type: 'QUALIFICATION',
        order: 1,
        status: 'COMPLETED',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: true,
        rulesetId: 'RULESET-KNOCKOUT',
      },
      {
        id: 'stage-ccl-groups',
        competitionId: 'CAF-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'Group Stage',
        slug: 'group-stage',
        type: 'GROUP_STAGE',
        order: 2,
        status: 'IN_PROGRESS',
        isGroupStage: true,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        groupsCount: 4,
        advancingTeamsCount: 8,
        rulesetId: 'RULESET-CAF-GROUP-STAGE',
      },
      {
        id: 'stage-ccl-knockout',
        competitionId: 'CAF-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 3,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-ccl-groups',
    hasGroups: true,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-CAF-GROUP-STAGE',
  },

  // ─── UEFA Champions League: Historic Format (2023/2024: 8 Groups of 4) ─────
  'UEFA-CHAMPIONS-LEAGUE:2023/2024': {
    id: 'UEFA-CHAMPIONS-LEAGUE:2023/2024',
    competitionId: 'UEFA-CHAMPIONS-LEAGUE',
    seasonId: '2023/2024',
    formatType: 'HYBRID',
    name: 'UEFA Champions League 32-Team Format (Historic)',
    description: '32 clubs in 8 groups of 4 followed by two-legged Round of 16, Quarter-finals, Semi-finals and Final.',
    stages: [
      {
        id: 'stage-ucl-2023-groups',
        competitionId: 'UEFA-CHAMPIONS-LEAGUE',
        seasonId: '2023/2024',
        name: 'Group Stage',
        slug: 'group-stage',
        type: 'GROUP_STAGE',
        order: 1,
        status: 'COMPLETED',
        isGroupStage: true,
        isLeaguePhase: false,
        isKnockout: false,
        isQualification: false,
        groupsCount: 8,
        advancingTeamsCount: 16,
        rulesetId: 'RULESET-STANDARD-3PT',
      },
      {
        id: 'stage-ucl-2023-knockout',
        competitionId: 'UEFA-CHAMPIONS-LEAGUE',
        seasonId: '2023/2024',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 2,
        status: 'COMPLETED',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-ucl-2023-groups',
    hasGroups: true,
    hasKnockout: true,
    hasLeagueTable: false,
    rulesetId: 'RULESET-STANDARD-3PT',
  },

  // ─── UEFA Champions League: Modern Format (2024/2025+ Single 36-Team League Phase)
  'UEFA-CHAMPIONS-LEAGUE:default': {
    id: 'UEFA-CHAMPIONS-LEAGUE:default',
    competitionId: 'UEFA-CHAMPIONS-LEAGUE',
    seasonId: 'default',
    formatType: 'HYBRID',
    name: 'UEFA Champions League 36-Team Swiss System',
    description: 'Single 36-team League Phase table (8 matches per team); top 8 advance directly to R16; 9th-24th to Knockout Play-offs.',
    stages: [
      {
        id: 'stage-ucl-league-phase',
        competitionId: 'UEFA-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'League Phase',
        slug: 'league-phase',
        type: 'LEAGUE_PHASE',
        order: 1,
        status: 'IN_PROGRESS',
        isGroupStage: false,
        isLeaguePhase: true,
        isKnockout: false,
        isQualification: false,
        rulesetId: 'RULESET-UEFA-LEAGUE-PHASE',
      },
      {
        id: 'stage-ucl-playoffs',
        competitionId: 'UEFA-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'Knockout Phase Play-offs',
        slug: 'play-offs',
        type: 'PLAYOFF',
        order: 2,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
      {
        id: 'stage-ucl-knockout',
        competitionId: 'UEFA-CHAMPIONS-LEAGUE',
        seasonId: 'default',
        name: 'Knockout Stage',
        slug: 'knockout-stage',
        type: 'KNOCKOUT',
        order: 3,
        status: 'UPCOMING',
        isGroupStage: false,
        isLeaguePhase: false,
        isKnockout: true,
        isQualification: false,
        rulesetId: 'RULESET-KNOCKOUT',
      },
    ],
    defaultStageId: 'stage-ucl-league-phase',
    hasGroups: false,
    hasKnockout: true,
    hasLeagueTable: true,
    rulesetId: 'RULESET-UEFA-LEAGUE-PHASE',
  },
};
