import {
  CanonicalCompetition,
  CompetitionGender,
  CompetitionAgeCategory,
  CompetitionType,
  CompetitionLevel,
  CompetitionTier,
  ConfederationCode,
  CompetitionStatus,
} from '@goalmills/types';

export const LEAGUE_LOGO_BASE = 'https://media.api-sports.io/football/leagues';
export const leagueLogo = (apiSportsId: number): string => `${LEAGUE_LOGO_BASE}/${apiSportsId}.png`;

/**
 * Master Canonical Competition Registry for GoalMills Football Platform.
 * Keys are canonical GoalMills competition IDs (e.g., 'ENG-PREMIER-LEAGUE', 'CAF-AFCON').
 */
export const CANONICAL_COMPETITIONS: Record<string, CanonicalCompetition> = {
  // ─── CAF & African Competitions ─────────────────────────────────────────────
  'CAF-AFCON': {
    id: 'CAF-AFCON',
    providerId: 6,
    providerName: 'allsportsapi',
    apiSportsId: 6,
    slug: 'afcon',
    name: 'Africa Cup of Nations',
    shortName: 'AFCON',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_NATIONAL',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 1,
    displayOrder: 1,
    logoUrl: leagueLogo(6),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'afcon',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-CHAMPIONS-LEAGUE': {
    id: 'CAF-CHAMPIONS-LEAGUE',
    providerId: 19,
    providerName: 'allsportsapi',
    apiSportsId: 12,
    slug: 'caf-champions-league',
    name: 'CAF Champions League',
    shortName: 'CAF CL',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 2,
    displayOrder: 2,
    logoUrl: leagueLogo(12),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'caf-champions-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-CONFEDERATION-CUP': {
    id: 'CAF-CONFEDERATION-CUP',
    providerId: 20,
    providerName: 'allsportsapi',
    apiSportsId: 20,
    slug: 'caf-confederation-cup',
    name: 'CAF Confederation Cup',
    shortName: 'CAF CC',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 3,
    displayOrder: 3,
    logoUrl: leagueLogo(20),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'caf-confederation-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-CHAN': {
    id: 'CAF-CHAN',
    providerId: 360,
    providerName: 'allsportsapi',
    apiSportsId: 321,
    slug: 'chan',
    name: 'African Nations Championship (CHAN)',
    shortName: 'CHAN',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_NATIONAL',
    level: 'CONFEDERATION',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 4,
    displayOrder: 4,
    logoUrl: leagueLogo(321),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'chan',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-WAFCON': {
    id: 'CAF-WAFCON',
    providerId: 365,
    providerName: 'allsportsapi',
    apiSportsId: 365,
    slug: 'afcon-women',
    name: "Women's Africa Cup of Nations (WAFCON)",
    shortName: 'WAFCON',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_NATIONAL',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: true,
    isMens: false,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 5,
    displayOrder: 5,
    logoUrl: leagueLogo(365),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'afcon-women',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-AFCON-U20': {
    id: 'CAF-AFCON-U20',
    providerId: 362,
    providerName: 'allsportsapi',
    apiSportsId: 322,
    slug: 'afcon-u20',
    name: 'AFCON U-20',
    shortName: 'AFCON U20',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'U20',
    competitionType: 'TOURNAMENT',
    level: 'CONFEDERATION',
    tier: 3,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: true,
    isSenior: false,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 6,
    displayOrder: 6,
    logoUrl: leagueLogo(322),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'afcon-u20',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CAF-AFCON-U17': {
    id: 'CAF-AFCON-U17',
    providerId: 363,
    providerName: 'allsportsapi',
    apiSportsId: 325,
    slug: 'afcon-u17',
    name: 'AFCON U-17',
    shortName: 'AFCON U17',
    countryCode: 'CAF',
    countryName: 'Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'U17',
    competitionType: 'TOURNAMENT',
    level: 'CONFEDERATION',
    tier: 3,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: true,
    isSenior: false,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 7,
    displayOrder: 7,
    logoUrl: leagueLogo(325),
    countryFlagUrl: 'https://media.api-sports.io/flags/africa.svg',
    canonicalSlug: 'afcon-u17',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── African Domestic Leagues ────────────────────────────────────────────────
  'NGA-NPFL': {
    id: 'NGA-NPFL',
    providerId: 247,
    providerName: 'allsportsapi',
    apiSportsId: 234,
    slug: 'npfl',
    name: 'NPFL (Nigeria)',
    shortName: 'NPFL',
    countryCode: 'NG',
    countryName: 'Nigeria',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 8,
    displayOrder: 8,
    logoUrl: leagueLogo(234),
    countryFlagUrl: 'https://media.api-sports.io/flags/ng.svg',
    canonicalSlug: 'npfl',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ZAF-PSL': {
    id: 'ZAF-PSL',
    providerId: 288,
    providerName: 'allsportsapi',
    apiSportsId: 288,
    slug: 'south-african-psl',
    name: 'Betway Premiership (PSL)',
    shortName: 'Betway PSL',
    countryCode: 'ZA',
    countryName: 'South Africa',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 9,
    displayOrder: 9,
    logoUrl: leagueLogo(288),
    countryFlagUrl: 'https://media.api-sports.io/flags/za.svg',
    canonicalSlug: 'south-african-psl',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'EGY-PREMIER-LEAGUE': {
    id: 'EGY-PREMIER-LEAGUE',
    providerId: 178,
    providerName: 'allsportsapi',
    apiSportsId: 233,
    slug: 'egyptian-premier-league',
    name: 'Egyptian Premier League',
    shortName: 'Egypt PL',
    countryCode: 'EG',
    countryName: 'Egypt',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 10,
    displayOrder: 10,
    logoUrl: leagueLogo(233),
    countryFlagUrl: 'https://media.api-sports.io/flags/eg.svg',
    canonicalSlug: 'egyptian-premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'MAR-BOTOLA-PRO': {
    id: 'MAR-BOTOLA-PRO',
    providerId: 233,
    providerName: 'allsportsapi',
    apiSportsId: 200,
    slug: 'botola-pro',
    name: 'Botola Pro Inwi',
    shortName: 'Botola Pro',
    countryCode: 'MA',
    countryName: 'Morocco',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 11,
    displayOrder: 11,
    logoUrl: leagueLogo(200),
    countryFlagUrl: 'https://media.api-sports.io/flags/ma.svg',
    canonicalSlug: 'botola-pro',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'GHA-PREMIER-LEAGUE': {
    id: 'GHA-PREMIER-LEAGUE',
    providerId: 198,
    providerName: 'allsportsapi',
    apiSportsId: 387,
    slug: 'ghanaian-premier-league',
    name: 'Ghana Premier League',
    shortName: 'Ghana PL',
    countryCode: 'GH',
    countryName: 'Ghana',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 12,
    displayOrder: 12,
    logoUrl: leagueLogo(387),
    countryFlagUrl: 'https://media.api-sports.io/flags/gh.svg',
    canonicalSlug: 'ghanaian-premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'DZA-LIGUE-1': {
    id: 'DZA-LIGUE-1',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 186,
    slug: 'algerian-ligue-1',
    name: 'Ligue 1 Mobilis (Algeria)',
    shortName: 'Algeria Ligue 1',
    countryCode: 'DZ',
    countryName: 'Algeria',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 13,
    displayOrder: 13,
    logoUrl: leagueLogo(186),
    countryFlagUrl: 'https://media.api-sports.io/flags/dz.svg',
    canonicalSlug: 'algerian-ligue-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'TUN-LIGUE-1': {
    id: 'TUN-LIGUE-1',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 202,
    slug: 'tunisian-ligue-1',
    name: 'Ligue Professionnelle 1 (Tunisia)',
    shortName: 'Tunisia LP1',
    countryCode: 'TN',
    countryName: 'Tunisia',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 14,
    displayOrder: 14,
    logoUrl: leagueLogo(202),
    countryFlagUrl: 'https://media.api-sports.io/flags/tn.svg',
    canonicalSlug: 'tunisian-ligue-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'TZA-PREMIER-LEAGUE': {
    id: 'TZA-PREMIER-LEAGUE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 412,
    slug: 'tanzania-premier-league',
    name: 'Tanzanian Premier League (NBC)',
    shortName: 'Tanzania PL',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 15,
    displayOrder: 15,
    logoUrl: leagueLogo(412),
    countryFlagUrl: 'https://media.api-sports.io/flags/tz.svg',
    canonicalSlug: 'tanzania-premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'COD-LINAFOOT': {
    id: 'COD-LINAFOOT',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 413,
    slug: 'dr-congo-linafoot',
    name: 'Linafoot (DR Congo)',
    shortName: 'Linafoot',
    countryCode: 'CD',
    countryName: 'DR Congo',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 16,
    displayOrder: 16,
    logoUrl: leagueLogo(413),
    countryFlagUrl: 'https://media.api-sports.io/flags/cd.svg',
    canonicalSlug: 'dr-congo-linafoot',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CIV-LIGUE-1': {
    id: 'CIV-LIGUE-1',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 414,
    slug: 'ivory-coast-ligue-1',
    name: 'Ligue 1 (Ivory Coast)',
    shortName: 'CIV Ligue 1',
    countryCode: 'CI',
    countryName: 'Ivory Coast',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 17,
    displayOrder: 17,
    logoUrl: leagueLogo(414),
    countryFlagUrl: 'https://media.api-sports.io/flags/ci.svg',
    canonicalSlug: 'ivory-coast-ligue-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ZMB-SUPER-LEAGUE': {
    id: 'ZMB-SUPER-LEAGUE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 415,
    slug: 'zambia-super-league',
    name: 'Zambia Super League',
    shortName: 'Zambia SL',
    countryCode: 'ZM',
    countryName: 'Zambia',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 18,
    displayOrder: 18,
    logoUrl: leagueLogo(415),
    countryFlagUrl: 'https://media.api-sports.io/flags/zm.svg',
    canonicalSlug: 'zambia-super-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'KEN-PREMIER-LEAGUE': {
    id: 'KEN-PREMIER-LEAGUE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 416,
    slug: 'kenya-premier-league',
    name: 'FKF Premier League (Kenya)',
    shortName: 'Kenya PL',
    countryCode: 'KE',
    countryName: 'Kenya',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 19,
    displayOrder: 19,
    logoUrl: leagueLogo(416),
    countryFlagUrl: 'https://media.api-sports.io/flags/ke.svg',
    canonicalSlug: 'kenya-premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'AGO-GIRABOLA': {
    id: 'AGO-GIRABOLA',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 417,
    slug: 'angola-girabola',
    name: 'Girabola (Angola)',
    shortName: 'Girabola',
    countryCode: 'AO',
    countryName: 'Angola',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 20,
    displayOrder: 20,
    logoUrl: leagueLogo(417),
    countryFlagUrl: 'https://media.api-sports.io/flags/ao.svg',
    canonicalSlug: 'angola-girabola',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UGA-PREMIER-LEAGUE': {
    id: 'UGA-PREMIER-LEAGUE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 418,
    slug: 'uganda-premier-league',
    name: 'Uganda Premier League',
    shortName: 'Uganda PL',
    countryCode: 'UG',
    countryName: 'Uganda',
    confederationCode: 'CAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 21,
    displayOrder: 21,
    logoUrl: leagueLogo(418),
    countryFlagUrl: 'https://media.api-sports.io/flags/ug.svg',
    canonicalSlug: 'uganda-premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── England Competitions ───────────────────────────────────────────────────
  'ENG-PREMIER-LEAGUE': {
    id: 'ENG-PREMIER-LEAGUE',
    providerId: 152,
    providerName: 'allsportsapi',
    apiSportsId: 39,
    slug: 'premier-league',
    name: 'Premier League',
    shortName: 'Premier League',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 22,
    displayOrder: 22,
    logoUrl: leagueLogo(39),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'premier-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-CHAMPIONSHIP': {
    id: 'ENG-CHAMPIONSHIP',
    providerId: 153,
    providerName: 'allsportsapi',
    apiSportsId: 40,
    slug: 'championship',
    name: 'EFL Championship',
    shortName: 'Championship',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 23,
    displayOrder: 23,
    logoUrl: leagueLogo(40),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'championship',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-LEAGUE-ONE': {
    id: 'ENG-LEAGUE-ONE',
    providerId: 154,
    providerName: 'allsportsapi',
    apiSportsId: 41,
    slug: 'league-one',
    name: 'EFL League One',
    shortName: 'League One',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 3,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 24,
    displayOrder: 24,
    logoUrl: leagueLogo(41),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'league-one',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-LEAGUE-TWO': {
    id: 'ENG-LEAGUE-TWO',
    providerId: 155,
    providerName: 'allsportsapi',
    apiSportsId: 42,
    slug: 'league-two',
    name: 'EFL League Two',
    shortName: 'League Two',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 4,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 25,
    displayOrder: 25,
    logoUrl: leagueLogo(42),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'league-two',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-FA-CUP': {
    id: 'ENG-FA-CUP',
    providerId: 146,
    providerName: 'allsportsapi',
    apiSportsId: 45,
    slug: 'fa-cup',
    name: 'FA Cup',
    shortName: 'FA Cup',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 26,
    displayOrder: 26,
    logoUrl: leagueLogo(45),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'fa-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-EFL-CUP': {
    id: 'ENG-EFL-CUP',
    providerId: 151,
    providerName: 'allsportsapi',
    apiSportsId: 48,
    slug: 'efl-league-cup',
    name: 'EFL Cup (Carabao Cup)',
    shortName: 'EFL Cup',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 27,
    displayOrder: 27,
    logoUrl: leagueLogo(48),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'efl-league-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ENG-WOMENS-SUPER-LEAGUE': {
    id: 'ENG-WOMENS-SUPER-LEAGUE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 44,
    slug: 'womens-super-league',
    name: "Barclays Women's Super League",
    shortName: 'WSL',
    countryCode: 'GB-ENG',
    countryName: 'England',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: true,
    isMens: false,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 28,
    displayOrder: 28,
    logoUrl: leagueLogo(44),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'womens-super-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── Spain Competitions ─────────────────────────────────────────────────────
  'ESP-LA-LIGA': {
    id: 'ESP-LA-LIGA',
    providerId: 302,
    providerName: 'allsportsapi',
    apiSportsId: 140,
    slug: 'la-liga',
    name: 'La Liga (EA Sports)',
    shortName: 'La Liga',
    countryCode: 'ES',
    countryName: 'Spain',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 29,
    displayOrder: 29,
    logoUrl: leagueLogo(140),
    countryFlagUrl: 'https://media.api-sports.io/flags/es.svg',
    canonicalSlug: 'la-liga',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ESP-SEGUNDA': {
    id: 'ESP-SEGUNDA',
    providerId: 301,
    providerName: 'allsportsapi',
    apiSportsId: 141,
    slug: 'segunda-division',
    name: 'LaLiga Hypermotion (Segunda)',
    shortName: 'Segunda',
    countryCode: 'ES',
    countryName: 'Spain',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 30,
    displayOrder: 30,
    logoUrl: leagueLogo(141),
    countryFlagUrl: 'https://media.api-sports.io/flags/es.svg',
    canonicalSlug: 'segunda-division',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ESP-COPA-DEL-REY': {
    id: 'ESP-COPA-DEL-REY',
    providerId: 300,
    providerName: 'allsportsapi',
    apiSportsId: 143,
    slug: 'copa-del-rey',
    name: 'Copa del Rey',
    shortName: 'Copa del Rey',
    countryCode: 'ES',
    countryName: 'Spain',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 31,
    displayOrder: 31,
    logoUrl: leagueLogo(143),
    countryFlagUrl: 'https://media.api-sports.io/flags/es.svg',
    canonicalSlug: 'copa-del-rey',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ESP-LIGA-F': {
    id: 'ESP-LIGA-F',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 142,
    slug: 'liga-f',
    name: 'Liga F (Spain Women)',
    shortName: 'Liga F',
    countryCode: 'ES',
    countryName: 'Spain',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: true,
    isMens: false,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 32,
    displayOrder: 32,
    logoUrl: leagueLogo(142),
    countryFlagUrl: 'https://media.api-sports.io/flags/es.svg',
    canonicalSlug: 'liga-f',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── Italy Competitions ─────────────────────────────────────────────────────
  'ITA-SERIE-A': {
    id: 'ITA-SERIE-A',
    providerId: 207,
    providerName: 'allsportsapi',
    apiSportsId: 135,
    slug: 'serie-a',
    name: 'Serie A (Enilive)',
    shortName: 'Serie A',
    countryCode: 'IT',
    countryName: 'Italy',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 33,
    displayOrder: 33,
    logoUrl: leagueLogo(135),
    countryFlagUrl: 'https://media.api-sports.io/flags/it.svg',
    canonicalSlug: 'serie-a',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ITA-SERIE-B': {
    id: 'ITA-SERIE-B',
    providerId: 206,
    providerName: 'allsportsapi',
    apiSportsId: 136,
    slug: 'serie-b',
    name: 'Serie BKT',
    shortName: 'Serie B',
    countryCode: 'IT',
    countryName: 'Italy',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 34,
    displayOrder: 34,
    logoUrl: leagueLogo(136),
    countryFlagUrl: 'https://media.api-sports.io/flags/it.svg',
    canonicalSlug: 'serie-b',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ITA-COPPA-ITALIA': {
    id: 'ITA-COPPA-ITALIA',
    providerId: 205,
    providerName: 'allsportsapi',
    apiSportsId: 137,
    slug: 'coppa-italia',
    name: 'Coppa Italia Frecciarossa',
    shortName: 'Coppa Italia',
    countryCode: 'IT',
    countryName: 'Italy',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 35,
    displayOrder: 35,
    logoUrl: leagueLogo(137),
    countryFlagUrl: 'https://media.api-sports.io/flags/it.svg',
    canonicalSlug: 'coppa-italia',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ITA-SERIE-A-FEMMINILE': {
    id: 'ITA-SERIE-A-FEMMINILE',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 139,
    slug: 'serie-a-femminile',
    name: 'Serie A Femminile',
    shortName: 'Serie A Fem',
    countryCode: 'IT',
    countryName: 'Italy',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: true,
    isMens: false,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 36,
    displayOrder: 36,
    logoUrl: leagueLogo(139),
    countryFlagUrl: 'https://media.api-sports.io/flags/it.svg',
    canonicalSlug: 'serie-a-femminile',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── Germany Competitions ───────────────────────────────────────────────────
  'GER-BUNDESLIGA': {
    id: 'GER-BUNDESLIGA',
    providerId: 175,
    providerName: 'allsportsapi',
    apiSportsId: 78,
    slug: 'bundesliga',
    name: 'Bundesliga',
    shortName: 'Bundesliga',
    countryCode: 'DE',
    countryName: 'Germany',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 37,
    displayOrder: 37,
    logoUrl: leagueLogo(78),
    countryFlagUrl: 'https://media.api-sports.io/flags/de.svg',
    canonicalSlug: 'bundesliga',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'GER-2-BUNDESLIGA': {
    id: 'GER-2-BUNDESLIGA',
    providerId: 176,
    providerName: 'allsportsapi',
    apiSportsId: 79,
    slug: '2-bundesliga',
    name: '2. Bundesliga',
    shortName: '2. Bundesliga',
    countryCode: 'DE',
    countryName: 'Germany',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 38,
    displayOrder: 38,
    logoUrl: leagueLogo(79),
    countryFlagUrl: 'https://media.api-sports.io/flags/de.svg',
    canonicalSlug: '2-bundesliga',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'GER-DFB-POKAL': {
    id: 'GER-DFB-POKAL',
    providerId: 173,
    providerName: 'allsportsapi',
    apiSportsId: 81,
    slug: 'dfb-pokal',
    name: 'DFB-Pokal',
    shortName: 'DFB-Pokal',
    countryCode: 'DE',
    countryName: 'Germany',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 39,
    displayOrder: 39,
    logoUrl: leagueLogo(81),
    countryFlagUrl: 'https://media.api-sports.io/flags/de.svg',
    canonicalSlug: 'dfb-pokal',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'GER-FRAUEN-BUNDESLIGA': {
    id: 'GER-FRAUEN-BUNDESLIGA',
    providerId: 0,
    providerName: 'allsportsapi',
    apiSportsId: 82,
    slug: 'frauen-bundesliga',
    name: 'Google Pixel Frauen-Bundesliga',
    shortName: 'Frauen Bundesliga',
    countryCode: 'DE',
    countryName: 'Germany',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'FEMALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: true,
    isMens: false,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 40,
    displayOrder: 40,
    logoUrl: leagueLogo(82),
    countryFlagUrl: 'https://media.api-sports.io/flags/de.svg',
    canonicalSlug: 'frauen-bundesliga',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── France Competitions ────────────────────────────────────────────────────
  'FRA-LIGUE-1': {
    id: 'FRA-LIGUE-1',
    providerId: 168,
    providerName: 'allsportsapi',
    apiSportsId: 61,
    slug: 'ligue-1',
    name: 'Ligue 1 McDonald’s',
    shortName: 'Ligue 1',
    countryCode: 'FR',
    countryName: 'France',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 41,
    displayOrder: 41,
    logoUrl: leagueLogo(61),
    countryFlagUrl: 'https://media.api-sports.io/flags/fr.svg',
    canonicalSlug: 'ligue-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'FRA-LIGUE-2': {
    id: 'FRA-LIGUE-2',
    providerId: 169,
    providerName: 'allsportsapi',
    apiSportsId: 62,
    slug: 'ligue-2',
    name: 'Ligue 2 BKT',
    shortName: 'Ligue 2',
    countryCode: 'FR',
    countryName: 'France',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 42,
    displayOrder: 42,
    logoUrl: leagueLogo(62),
    countryFlagUrl: 'https://media.api-sports.io/flags/fr.svg',
    canonicalSlug: 'ligue-2',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'FRA-COUPE-DE-FRANCE': {
    id: 'FRA-COUPE-DE-FRANCE',
    providerId: 166,
    providerName: 'allsportsapi',
    apiSportsId: 66,
    slug: 'coupe-de-france',
    name: 'Coupe de France',
    shortName: 'Coupe de France',
    countryCode: 'FR',
    countryName: 'France',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CUP',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 43,
    displayOrder: 43,
    logoUrl: leagueLogo(66),
    countryFlagUrl: 'https://media.api-sports.io/flags/fr.svg',
    canonicalSlug: 'coupe-de-france',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── UEFA European Club Cups ────────────────────────────────────────────────
  'UEFA-CHAMPIONS-LEAGUE': {
    id: 'UEFA-CHAMPIONS-LEAGUE',
    providerId: 3,
    providerName: 'allsportsapi',
    apiSportsId: 2,
    slug: 'champions-league',
    name: 'UEFA Champions League',
    shortName: 'UCL',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 44,
    displayOrder: 44,
    logoUrl: leagueLogo(2),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'champions-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UEFA-EUROPA-LEAGUE': {
    id: 'UEFA-EUROPA-LEAGUE',
    providerId: 4,
    providerName: 'allsportsapi',
    apiSportsId: 3,
    slug: 'europa-league',
    name: 'UEFA Europa League',
    shortName: 'UEL',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 45,
    displayOrder: 45,
    logoUrl: leagueLogo(3),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'europa-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UEFA-CONFERENCE-LEAGUE': {
    id: 'UEFA-CONFERENCE-LEAGUE',
    providerId: 683,
    providerName: 'allsportsapi',
    apiSportsId: 848,
    slug: 'conference-league',
    name: 'UEFA Conference League',
    shortName: 'UECL',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 46,
    displayOrder: 46,
    logoUrl: leagueLogo(848),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'conference-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UEFA-SUPER-CUP': {
    id: 'UEFA-SUPER-CUP',
    providerId: 2,
    providerName: 'allsportsapi',
    apiSportsId: 531,
    slug: 'uefa-super-cup',
    name: 'UEFA Super Cup',
    shortName: 'UEFA Super Cup',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'SUPER_CUP',
    level: 'CONFEDERATION',
    tier: 2,
    season: '2026',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 47,
    displayOrder: 47,
    logoUrl: leagueLogo(531),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'uefa-super-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── FIFA & International Competitions ──────────────────────────────────────
  'FIFA-WORLD-CUP': {
    id: 'FIFA-WORLD-CUP',
    providerId: 28,
    providerName: 'allsportsapi',
    apiSportsId: 1,
    slug: 'fifa-world-cup',
    name: 'FIFA World Cup 2026',
    shortName: 'World Cup',
    countryCode: 'FIFA',
    countryName: 'International',
    confederationCode: 'FIFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'WORLD_CUP',
    level: 'GLOBAL',
    tier: 1,
    season: '2026',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: false,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 48,
    displayOrder: 48,
    logoUrl: leagueLogo(1),
    countryFlagUrl: 'https://media.api-sports.io/flags/world.svg',
    canonicalSlug: 'fifa-world-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'FIFA-CLUB-WORLD-CUP': {
    id: 'FIFA-CLUB-WORLD-CUP',
    providerId: 531,
    providerName: 'allsportsapi',
    apiSportsId: 15,
    slug: 'fifa-club-world-cup',
    name: 'FIFA Club World Cup',
    shortName: 'Club World Cup',
    countryCode: 'FIFA',
    countryName: 'International',
    confederationCode: 'FIFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'TOURNAMENT',
    level: 'GLOBAL',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: false,
    isInternational: true,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 49,
    displayOrder: 49,
    logoUrl: leagueLogo(15),
    countryFlagUrl: 'https://media.api-sports.io/flags/world.svg',
    canonicalSlug: 'fifa-club-world-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'FIFA-WORLD-CUP-QUALIFIERS': {
    id: 'FIFA-WORLD-CUP-QUALIFIERS',
    providerId: 29,
    providerName: 'allsportsapi',
    apiSportsId: 32,
    slug: 'fifa-wc-qualifiers',
    name: 'FIFA World Cup Qualifiers (CAF & Global)',
    shortName: 'WC Qualifiers',
    countryCode: 'FIFA',
    countryName: 'International',
    confederationCode: 'FIFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'QUALIFIER',
    level: 'GLOBAL',
    tier: 2,
    season: '2026',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: false,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 50,
    displayOrder: 50,
    logoUrl: leagueLogo(32),
    countryFlagUrl: 'https://media.api-sports.io/flags/world.svg',
    canonicalSlug: 'fifa-wc-qualifiers',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UEFA-EURO': {
    id: 'UEFA-EURO',
    providerId: 1,
    providerName: 'allsportsapi',
    apiSportsId: 4,
    slug: 'uefa-euro',
    name: 'UEFA European Championship',
    shortName: 'UEFA EURO',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_NATIONAL',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2028',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 51,
    displayOrder: 51,
    logoUrl: leagueLogo(4),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'uefa-euro',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'UEFA-NATIONS-LEAGUE': {
    id: 'UEFA-NATIONS-LEAGUE',
    providerId: 5,
    providerName: 'allsportsapi',
    apiSportsId: 5,
    slug: 'uefa-nations-league',
    name: 'UEFA Nations League',
    shortName: 'Nations League',
    countryCode: 'UEFA',
    countryName: 'Europe',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'NATIONS_LEAGUE',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 52,
    displayOrder: 52,
    logoUrl: leagueLogo(5),
    countryFlagUrl: 'https://media.api-sports.io/flags/eu.svg',
    canonicalSlug: 'uefa-nations-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── CONMEBOL Competitions ──────────────────────────────────────────────────
  'CONMEBOL-COPA-AMERICA': {
    id: 'CONMEBOL-COPA-AMERICA',
    providerId: 17,
    providerName: 'allsportsapi',
    apiSportsId: 9,
    slug: 'copa-america',
    name: 'Copa América',
    shortName: 'Copa América',
    countryCode: 'CONMEBOL',
    countryName: 'South America',
    confederationCode: 'CONMEBOL',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_NATIONAL',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2028',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: true,
    isNationalTeam: true,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 53,
    displayOrder: 53,
    logoUrl: leagueLogo(9),
    countryFlagUrl: 'https://media.api-sports.io/flags/south-america.svg',
    canonicalSlug: 'copa-america',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CONMEBOL-LIBERTADORES': {
    id: 'CONMEBOL-LIBERTADORES',
    providerId: 13,
    providerName: 'allsportsapi',
    apiSportsId: 13,
    slug: 'copa-libertadores',
    name: 'Copa CONMEBOL Libertadores',
    shortName: 'Libertadores',
    countryCode: 'CONMEBOL',
    countryName: 'South America',
    confederationCode: 'CONMEBOL',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: true,
    isIndexable: true,
    priorityRank: 54,
    displayOrder: 54,
    logoUrl: leagueLogo(13),
    countryFlagUrl: 'https://media.api-sports.io/flags/south-america.svg',
    canonicalSlug: 'copa-libertadores',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CONMEBOL-SUDAMERICANA': {
    id: 'CONMEBOL-SUDAMERICANA',
    providerId: 14,
    providerName: 'allsportsapi',
    apiSportsId: 11,
    slug: 'copa-sudamericana',
    name: 'Copa CONMEBOL Sudamericana',
    shortName: 'Sudamericana',
    countryCode: 'CONMEBOL',
    countryName: 'South America',
    confederationCode: 'CONMEBOL',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 2,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 55,
    displayOrder: 55,
    logoUrl: leagueLogo(11),
    countryFlagUrl: 'https://media.api-sports.io/flags/south-america.svg',
    canonicalSlug: 'copa-sudamericana',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'BRA-SERIE-A': {
    id: 'BRA-SERIE-A',
    providerId: 99,
    providerName: 'allsportsapi',
    apiSportsId: 71,
    slug: 'brasileirao',
    name: 'Brasileirão Série A (Betano)',
    shortName: 'Brasileirão',
    countryCode: 'BR',
    countryName: 'Brazil',
    confederationCode: 'CONMEBOL',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 56,
    displayOrder: 56,
    logoUrl: leagueLogo(71),
    countryFlagUrl: 'https://media.api-sports.io/flags/br.svg',
    canonicalSlug: 'brasileirao',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'ARG-PRIMERA-DIVISION': {
    id: 'ARG-PRIMERA-DIVISION',
    providerId: 135,
    providerName: 'allsportsapi',
    apiSportsId: 128,
    slug: 'liga-profesional',
    name: 'Liga Profesional de Fútbol (Argentina)',
    shortName: 'Argentina Liga',
    countryCode: 'AR',
    countryName: 'Argentina',
    confederationCode: 'CONMEBOL',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 57,
    displayOrder: 57,
    logoUrl: leagueLogo(128),
    countryFlagUrl: 'https://media.api-sports.io/flags/ar.svg',
    canonicalSlug: 'liga-profesional',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── Other European Domestic Leagues ────────────────────────────────────────
  'NLD-EREDIVISIE': {
    id: 'NLD-EREDIVISIE',
    providerId: 244,
    providerName: 'allsportsapi',
    apiSportsId: 88,
    slug: 'eredivisie',
    name: 'Eredivisie',
    shortName: 'Eredivisie',
    countryCode: 'NL',
    countryName: 'Netherlands',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 58,
    displayOrder: 58,
    logoUrl: leagueLogo(88),
    countryFlagUrl: 'https://media.api-sports.io/flags/nl.svg',
    canonicalSlug: 'eredivisie',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'PRT-PRIMEIRA-LIGA': {
    id: 'PRT-PRIMEIRA-LIGA',
    providerId: 266,
    providerName: 'allsportsapi',
    apiSportsId: 94,
    slug: 'liga-portugal',
    name: 'Liga Portugal Betclic',
    shortName: 'Liga Portugal',
    countryCode: 'PT',
    countryName: 'Portugal',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 59,
    displayOrder: 59,
    logoUrl: leagueLogo(94),
    countryFlagUrl: 'https://media.api-sports.io/flags/pt.svg',
    canonicalSlug: 'liga-portugal',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'SCO-PREMIERSHIP': {
    id: 'SCO-PREMIERSHIP',
    providerId: 179,
    providerName: 'allsportsapi',
    apiSportsId: 179,
    slug: 'scottish-premiership',
    name: 'William Hill Premiership (Scotland)',
    shortName: 'Scottish Prem',
    countryCode: 'GB-SCT',
    countryName: 'Scotland',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 60,
    displayOrder: 60,
    logoUrl: leagueLogo(179),
    countryFlagUrl: 'https://media.api-sports.io/flags/gb.svg',
    canonicalSlug: 'scottish-premiership',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'TUR-SUPER-LIG': {
    id: 'TUR-SUPER-LIG',
    providerId: 322,
    providerName: 'allsportsapi',
    apiSportsId: 203,
    slug: 'turkish-super-lig',
    name: 'Trendyol Süper Lig (Turkey)',
    shortName: 'Süper Lig',
    countryCode: 'TR',
    countryName: 'Turkey',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 61,
    displayOrder: 61,
    logoUrl: leagueLogo(203),
    countryFlagUrl: 'https://media.api-sports.io/flags/tr.svg',
    canonicalSlug: 'turkish-super-lig',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'BEL-PRO-LEAGUE': {
    id: 'BEL-PRO-LEAGUE',
    providerId: 344,
    providerName: 'allsportsapi',
    apiSportsId: 144,
    slug: 'belgian-pro-league',
    name: 'Jupiler Pro League (Belgium)',
    shortName: 'Pro League',
    countryCode: 'BE',
    countryName: 'Belgium',
    confederationCode: 'UEFA',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 62,
    displayOrder: 62,
    logoUrl: leagueLogo(144),
    countryFlagUrl: 'https://media.api-sports.io/flags/be.svg',
    canonicalSlug: 'belgian-pro-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

  // ─── CONCACAF & Other Global Competitions ───────────────────────────────────
  'USA-MLS': {
    id: 'USA-MLS',
    providerId: 330,
    providerName: 'allsportsapi',
    apiSportsId: 253,
    slug: 'mls',
    name: 'Major League Soccer (MLS)',
    shortName: 'MLS',
    countryCode: 'US',
    countryName: 'United States',
    confederationCode: 'CONCACAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 63,
    displayOrder: 63,
    logoUrl: leagueLogo(253),
    countryFlagUrl: 'https://media.api-sports.io/flags/us.svg',
    canonicalSlug: 'mls',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'SAU-PRO-LEAGUE': {
    id: 'SAU-PRO-LEAGUE',
    providerId: 278,
    providerName: 'allsportsapi',
    apiSportsId: 307,
    slug: 'saudi-pro-league',
    name: 'Roshn Saudi League (SPL)',
    shortName: 'Saudi Pro League',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    confederationCode: 'AFC',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'LEAGUE',
    level: 'DOMESTIC',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: true,
    isContinental: false,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 64,
    displayOrder: 64,
    logoUrl: leagueLogo(307),
    countryFlagUrl: 'https://media.api-sports.io/flags/sa.svg',
    canonicalSlug: 'saudi-pro-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'AFC-CHAMPIONS-LEAGUE': {
    id: 'AFC-CHAMPIONS-LEAGUE',
    providerId: 16,
    providerName: 'allsportsapi',
    apiSportsId: 17,
    slug: 'afc-champions-league',
    name: 'AFC Champions League Elite',
    shortName: 'AFC CL',
    countryCode: 'AFC',
    countryName: 'Asia',
    confederationCode: 'AFC',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 65,
    displayOrder: 65,
    logoUrl: leagueLogo(17),
    countryFlagUrl: 'https://media.api-sports.io/flags/asia.svg',
    canonicalSlug: 'afc-champions-league',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  'CONCACAF-CHAMPIONS-CUP': {
    id: 'CONCACAF-CHAMPIONS-CUP',
    providerId: 489,
    providerName: 'allsportsapi',
    apiSportsId: 16,
    slug: 'concacaf-champions-cup',
    name: 'CONCACAF Champions Cup',
    shortName: 'CONCACAF CC',
    countryCode: 'CONCACAF',
    countryName: 'North America',
    confederationCode: 'CONCACAF',
    sport: 'football',
    gender: 'MALE',
    ageCategory: 'SENIOR',
    competitionType: 'CONTINENTAL_CLUB',
    level: 'CONFEDERATION',
    tier: 1,
    season: '2026/2027',
    status: 'ACTIVE',
    isDomestic: false,
    isContinental: true,
    isInternational: false,
    isNationalTeam: false,
    isYouth: false,
    isSenior: true,
    isWomens: false,
    isMens: true,
    isFeatured: false,
    isIndexable: true,
    priorityRank: 66,
    displayOrder: 66,
    logoUrl: leagueLogo(16),
    countryFlagUrl: 'https://media.api-sports.io/flags/north-america.svg',
    canonicalSlug: 'concacaf-champions-cup',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
};

export const CANONICAL_COMPETITIONS_LIST: CanonicalCompetition[] =
  Object.values(CANONICAL_COMPETITIONS).sort((a, b) => a.priorityRank - b.priorityRank);

// Fast slug & provider lookup maps
const SLUG_MAP = new Map<string, CanonicalCompetition>();
const PROVIDER_ID_MAP = new Map<number, CanonicalCompetition>();

for (const comp of CANONICAL_COMPETITIONS_LIST) {
  SLUG_MAP.set(comp.slug.toLowerCase(), comp);
  SLUG_MAP.set(comp.id.toLowerCase(), comp);
  if (comp.providerId > 0) {
    PROVIDER_ID_MAP.set(comp.providerId, comp);
  }
}

export function getAllCanonicalCompetitions(): CanonicalCompetition[] {
  return CANONICAL_COMPETITIONS_LIST;
}

export function getCanonicalCompetition(idOrSlug: string): CanonicalCompetition | undefined {
  if (!idOrSlug) return undefined;
  const normalized = idOrSlug.trim().toLowerCase();
  return SLUG_MAP.get(normalized) || CANONICAL_COMPETITIONS[idOrSlug.toUpperCase()];
}

export function getCanonicalCompetitionByProviderId(
  providerId: number | string
): CanonicalCompetition | undefined {
  const num = typeof providerId === 'string' ? parseInt(providerId, 10) : providerId;
  if (isNaN(num) || num <= 0) return undefined;
  return PROVIDER_ID_MAP.get(num);
}

export function getCompetitionsByCountry(countryCode: string): CanonicalCompetition[] {
  const code = countryCode.toUpperCase();
  return CANONICAL_COMPETITIONS_LIST.filter(
    (c) => c.countryCode === code || c.countryName.toUpperCase() === code
  ).sort((a, b) => a.priorityRank - b.priorityRank);
}

export function getCompetitionsByConfederation(
  confed: ConfederationCode
): CanonicalCompetition[] {
  return CANONICAL_COMPETITIONS_LIST.filter((c) => c.confederationCode === confed).sort(
    (a, b) => a.priorityRank - b.priorityRank
  );
}

export function getFeaturedCompetitions(): CanonicalCompetition[] {
  return CANONICAL_COMPETITIONS_LIST.filter((c) => c.isFeatured).sort(
    (a, b) => a.priorityRank - b.priorityRank
  );
}

export function getAfricaPriorityCompetitions(): CanonicalCompetition[] {
  return CANONICAL_COMPETITIONS_LIST.filter((c) => c.confederationCode === 'CAF').sort(
    (a, b) => a.priorityRank - b.priorityRank
  );
}

export function getTop5EuropeanCompetitions(): CanonicalCompetition[] {
  const top5Countries = new Set(['GB-ENG', 'ES', 'IT', 'DE', 'FR']);
  return CANONICAL_COMPETITIONS_LIST.filter(
    (c) => top5Countries.has(c.countryCode) && c.tier === 1 && c.isMens && c.isDomestic
  ).sort((a, b) => a.priorityRank - b.priorityRank);
}
