import { CountryRecord } from '@goalmills/types';

export const COUNTRIES_REGISTRY: Record<string, CountryRecord> = {
  'GB-ENG': {
    code: 'GB-ENG',
    name: 'England',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/gb.svg',
    priorityRank: 1,
    isFeatured: true,
    priorityCompetitions: [
      'ENG-PREMIER-LEAGUE',
      'ENG-CHAMPIONSHIP',
      'ENG-LEAGUE-ONE',
      'ENG-LEAGUE-TWO',
      'ENG-FA-CUP',
      'ENG-WOMENS-SUPER-LEAGUE',
    ],
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/es.svg',
    priorityRank: 2,
    isFeatured: true,
    priorityCompetitions: [
      'ESP-LA-LIGA',
      'ESP-SEGUNDA',
      'ESP-PRIMERA-FEDERACION',
      'ESP-COPA-DEL-REY',
      'ESP-SEGUNDA-FEDERACION',
      'ESP-LIGA-F',
    ],
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/it.svg',
    priorityRank: 3,
    isFeatured: true,
    priorityCompetitions: [
      'ITA-SERIE-A',
      'ITA-SERIE-B',
      'ITA-COPPA-ITALIA',
      'ITA-SERIE-C',
      'ITA-COPPA-ITALIA-SERIE-C',
      'ITA-SERIE-A-FEMMINILE',
    ],
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/de.svg',
    priorityRank: 4,
    isFeatured: true,
    priorityCompetitions: [
      'GER-BUNDESLIGA',
      'GER-2-BUNDESLIGA',
      'GER-3-LIGA',
      'GER-REGIONALLIGA',
      'GER-DFB-POKAL',
      'GER-FRAUEN-BUNDESLIGA',
    ],
  },
  FR: {
    code: 'FR',
    name: 'France',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/fr.svg',
    priorityRank: 5,
    isFeatured: true,
    priorityCompetitions: [
      'FRA-LIGUE-1',
      'FRA-LIGUE-2',
      'FRA-NATIONAL',
      'FRA-NATIONAL-2',
      'FRA-COUPE-DE-FRANCE',
      'FRA-DIVISION-1-FEMININE',
    ],
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ng.svg',
    priorityRank: 6,
    isFeatured: true,
    priorityCompetitions: ['NGA-NPFL', 'NGA-FEDERATION-CUP'],
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/za.svg',
    priorityRank: 7,
    isFeatured: true,
    priorityCompetitions: ['ZAF-PSL', 'ZAF-NEDBANK-CUP'],
  },
  EG: {
    code: 'EG',
    name: 'Egypt',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/eg.svg',
    priorityRank: 8,
    isFeatured: true,
    priorityCompetitions: ['EGY-PREMIER-LEAGUE', 'EGY-CUP'],
  },
  MA: {
    code: 'MA',
    name: 'Morocco',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ma.svg',
    priorityRank: 9,
    isFeatured: true,
    priorityCompetitions: ['MAR-BOTOLA-PRO', 'MAR-THRONE-CUP'],
  },
  GH: {
    code: 'GH',
    name: 'Ghana',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/gh.svg',
    priorityRank: 10,
    isFeatured: true,
    priorityCompetitions: ['GHA-PREMIER-LEAGUE', 'GHA-FA-CUP'],
  },
  DZ: {
    code: 'DZ',
    name: 'Algeria',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/dz.svg',
    priorityRank: 11,
    isFeatured: true,
    priorityCompetitions: ['DZA-LIGUE-1', 'DZA-CUP'],
  },
  TN: {
    code: 'TN',
    name: 'Tunisia',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/tn.svg',
    priorityRank: 12,
    isFeatured: true,
    priorityCompetitions: ['TUN-LIGUE-1', 'TUN-CUP'],
  },
  TZ: {
    code: 'TZ',
    name: 'Tanzania',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/tz.svg',
    priorityRank: 13,
    isFeatured: false,
    priorityCompetitions: ['TZA-PREMIER-LEAGUE'],
  },
  CD: {
    code: 'CD',
    name: 'DR Congo',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/cd.svg',
    priorityRank: 14,
    isFeatured: false,
    priorityCompetitions: ['COD-LINAFOOT'],
  },
  CI: {
    code: 'CI',
    name: 'Ivory Coast',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ci.svg',
    priorityRank: 15,
    isFeatured: false,
    priorityCompetitions: ['CIV-LIGUE-1'],
  },
  ZM: {
    code: 'ZM',
    name: 'Zambia',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/zm.svg',
    priorityRank: 16,
    isFeatured: false,
    priorityCompetitions: ['ZMB-SUPER-LEAGUE'],
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ke.svg',
    priorityRank: 17,
    isFeatured: false,
    priorityCompetitions: ['KEN-PREMIER-LEAGUE'],
  },
  AO: {
    code: 'AO',
    name: 'Angola',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ao.svg',
    priorityRank: 18,
    isFeatured: false,
    priorityCompetitions: ['AGO-GIRABOLA'],
  },
  UG: {
    code: 'UG',
    name: 'Uganda',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/ug.svg',
    priorityRank: 19,
    isFeatured: false,
    priorityCompetitions: ['UGA-PREMIER-LEAGUE'],
  },
  SN: {
    code: 'SN',
    name: 'Senegal',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/sn.svg',
    priorityRank: 20,
    isFeatured: false,
    priorityCompetitions: ['SEN-LIGUE-1'],
  },
  CM: {
    code: 'CM',
    name: 'Cameroon',
    confederationCode: 'CAF',
    flagUrl: 'https://media.api-sports.io/flags/cm.svg',
    priorityRank: 21,
    isFeatured: false,
    priorityCompetitions: ['CMR-ELITE-ONE'],
  },
  PT: {
    code: 'PT',
    name: 'Portugal',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/pt.svg',
    priorityRank: 22,
    isFeatured: true,
    priorityCompetitions: ['PRT-PRIMEIRA-LIGA', 'PRT-TACA-DE-PORTUGAL'],
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/nl.svg',
    priorityRank: 23,
    isFeatured: true,
    priorityCompetitions: ['NLD-EREDIVISIE', 'NLD-KNVB-BEKER'],
  },
  'GB-SCT': {
    code: 'GB-SCT',
    name: 'Scotland',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/gb.svg',
    priorityRank: 24,
    isFeatured: false,
    priorityCompetitions: ['SCO-PREMIERSHIP'],
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/be.svg',
    priorityRank: 25,
    isFeatured: false,
    priorityCompetitions: ['BEL-PRO-LEAGUE'],
  },
  TR: {
    code: 'TR',
    name: 'Turkey',
    confederationCode: 'UEFA',
    flagUrl: 'https://media.api-sports.io/flags/tr.svg',
    priorityRank: 26,
    isFeatured: false,
    priorityCompetitions: ['TUR-SUPER-LIG'],
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    confederationCode: 'CONMEBOL',
    flagUrl: 'https://media.api-sports.io/flags/br.svg',
    priorityRank: 27,
    isFeatured: true,
    priorityCompetitions: ['BRA-SERIE-A', 'BRA-COPA-DO-BRASIL'],
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    confederationCode: 'CONMEBOL',
    flagUrl: 'https://media.api-sports.io/flags/ar.svg',
    priorityRank: 28,
    isFeatured: true,
    priorityCompetitions: ['ARG-PRIMERA-DIVISION', 'ARG-COPA-ARGENTINA'],
  },
  US: {
    code: 'US',
    name: 'United States',
    confederationCode: 'CONCACAF',
    flagUrl: 'https://media.api-sports.io/flags/us.svg',
    priorityRank: 29,
    isFeatured: true,
    priorityCompetitions: ['USA-MLS', 'USA-OPEN-CUP'],
  },
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    confederationCode: 'AFC',
    flagUrl: 'https://media.api-sports.io/flags/sa.svg',
    priorityRank: 30,
    isFeatured: true,
    priorityCompetitions: ['SAU-PRO-LEAGUE', 'SAU-KINGS-CUP'],
  },
};

export function getCountry(code: string): CountryRecord | undefined {
  return COUNTRIES_REGISTRY[code];
}

export function getAllCountries(): CountryRecord[] {
  return Object.values(COUNTRIES_REGISTRY).sort((a, b) => a.priorityRank - b.priorityRank);
}

export function getCountriesByConfederation(confed: string): CountryRecord[] {
  return Object.values(COUNTRIES_REGISTRY)
    .filter((c) => c.confederationCode === confed)
    .sort((a, b) => a.priorityRank - b.priorityRank);
}
